"""AUTO-GENERATED integration oracle for port_main_wrappers (gen_integration_oracle.py)."""
import os, sys, json, importlib.util

MODS = {}
def _load(rel):
    _repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if _repo not in sys.path: sys.path.insert(0, _repo)
    for base in sys.path:
        cand = os.path.join(base, rel)
        try:
            spec = importlib.util.spec_from_file_location('live_' + rel.replace('/', '_').replace('.', '_'), cand)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            return mod
        except Exception:
            continue
    return None
MODS['hermes_cli.main'] = _load('hermes_cli/main.py')

DISPATCH = {
    'main_u_exit_after_oneshot': ('hermes_cli.main', '_exit_after_oneshot'),
    'main_u_cleanup_oneshot_runtime': ('hermes_cli.main', '_cleanup_oneshot_runtime'),
    'main_u_run_and_exit_oneshot': ('hermes_cli.main', '_run_and_exit_oneshot'),
    'main_u_set_process_title': ('hermes_cli.main', '_set_process_title'),
    'main_u_config_default_interface_early': ('hermes_cli.main', '_config_default_interface_early'),
    'main_u_wants_tui_early': ('hermes_cli.main', '_wants_tui_early'),
    'main_u_suppress_mouse_residue_early': ('hermes_cli.main', '_suppress_mouse_residue_early'),
    'main_u_is_termux_startup_environment_fast': ('hermes_cli.main', '_is_termux_startup_environment_fast'),
    'main_u_is_termux_fast_version_argv': ('hermes_cli.main', '_is_termux_fast_version_argv'),
    'main_u_read_openai_version_fast': ('hermes_cli.main', '_read_openai_version_fast'),
    'main_u_print_fast_version_info': ('hermes_cli.main', '_print_fast_version_info'),
    'main_u_try_termux_ultrafast_version': ('hermes_cli.main', '_try_termux_ultrafast_version'),
    'main_u_require_tty': ('hermes_cli.main', '_require_tty'),
    'main_u_apply_profile_override': ('hermes_cli.main', '_apply_profile_override'),
    'main_u_is_termux_startup_environment': ('hermes_cli.main', '_is_termux_startup_environment'),
    'main_u_termux_bundled_skills_fingerprint': ('hermes_cli.main', '_termux_bundled_skills_fingerprint'),
    'main_u_termux_bundled_skills_stamp_path': ('hermes_cli.main', '_termux_bundled_skills_stamp_path'),
    'main_u_termux_bundled_skills_sync_needed': ('hermes_cli.main', '_termux_bundled_skills_sync_needed'),
    'main_u_mark_termux_bundled_skills_synced': ('hermes_cli.main', '_mark_termux_bundled_skills_synced'),
    'main_u_sync_bundled_skills_for_startup': ('hermes_cli.main', '_sync_bundled_skills_for_startup'),
    'main_u_termux_should_prefetch_update_check': ('hermes_cli.main', '_termux_should_prefetch_update_check'),
    'main_u_has_any_provider_configured': ('hermes_cli.main', '_has_any_provider_configured'),
    'main_u_session_browse_picker': ('hermes_cli.main', '_session_browse_picker'),
    'main_u_resolve_last_session': ('hermes_cli.main', '_resolve_last_session'),
    'main_u_probe_container': ('hermes_cli.main', '_probe_container'),
    'main_u_exec_in_container': ('hermes_cli.main', '_exec_in_container'),
    'main_u_resolve_session_by_name_or_id': ('hermes_cli.main', '_resolve_session_by_name_or_id'),
    'main_u_print_tui_exit_summary': ('hermes_cli.main', '_print_tui_exit_summary'),
    'main_u_termux_workspace_install_context': ('hermes_cli.main', '_termux_workspace_install_context'),
    'main_u_tui_need_npm_install': ('hermes_cli.main', '_tui_need_npm_install'),
    'main_u_iter_tui_build_inputs': ('hermes_cli.main', '_iter_tui_build_inputs'),
    'main_u_tui_need_rebuild': ('hermes_cli.main', '_tui_need_rebuild'),
    'main_u_ensure_tui_node': ('hermes_cli.main', '_ensure_tui_node'),
    'main_u_find_bundled_tui': ('hermes_cli.main', '_find_bundled_tui'),
    'main_u_make_tui_argv': ('hermes_cli.main', '_make_tui_argv'),
    'main_u_normalize_tui_toolsets': ('hermes_cli.main', '_normalize_tui_toolsets'),
    'main_u_resolve_tui_heap_mb': ('hermes_cli.main', '_resolve_tui_heap_mb'),
    'main_u_safe_tui_cwd': ('hermes_cli.main', '_safe_tui_cwd'),
    'main_u_apply_tui_python_env': ('hermes_cli.main', '_apply_tui_python_env'),
    'main_u_launch_tui': ('hermes_cli.main', '_launch_tui'),
    'main_u_pin_kanban_board_env': ('hermes_cli.main', '_pin_kanban_board_env'),
    'main_u_sync_bundled_skills_quietly': ('hermes_cli.main', '_sync_bundled_skills_quietly'),
    'main_u_resolve_use_tui': ('hermes_cli.main', '_resolve_use_tui'),
    'main_cmd_chat': ('hermes_cli.main', 'cmd_chat'),
    'main_cmd_proxy': ('hermes_cli.main', 'cmd_proxy'),
    'main_cmd_whatsapp': ('hermes_cli.main', 'cmd_whatsapp'),
    'main_cmd_whatsapp_cloud': ('hermes_cli.main', 'cmd_whatsapp_cloud'),
    'main_u_is_profile_api_key_provider': ('hermes_cli.main', '_is_profile_api_key_provider'),
    'main_select_provider_and_model': ('hermes_cli.main', 'select_provider_and_model'),
    'main_u_clear_stale_openai_base_url': ('hermes_cli.main', '_clear_stale_openai_base_url'),
    'main_u_all_aux_tasks': ('hermes_cli.main', '_all_aux_tasks'),
    'main_u_format_aux_current': ('hermes_cli.main', '_format_aux_current'),
    'main_u_save_aux_choice': ('hermes_cli.main', '_save_aux_choice'),
    'main_u_reset_aux_to_auto': ('hermes_cli.main', '_reset_aux_to_auto'),
    'main_u_aux_config_menu': ('hermes_cli.main', '_aux_config_menu'),
    'main_u_aux_select_for_task': ('hermes_cli.main', '_aux_select_for_task'),
    'main_u_aux_flow_provider_model': ('hermes_cli.main', '_aux_flow_provider_model'),
    'main_u_aux_flow_custom_endpoint': ('hermes_cli.main', '_aux_flow_custom_endpoint'),
    'main_u_prompt_provider_choice': ('hermes_cli.main', '_prompt_provider_choice'),
    'main_u_prompt_custom_api_mode_selection': ('hermes_cli.main', '_prompt_custom_api_mode_selection'),
    'main_u_custom_provider_api_key_config_value': ('hermes_cli.main', '_custom_provider_api_key_config_value'),
    'main_u_custom_provider_base_url_config_value': ('hermes_cli.main', '_custom_provider_base_url_config_value'),
    'main_u_save_custom_provider': ('hermes_cli.main', '_save_custom_provider'),
    'main_u_remove_custom_provider': ('hermes_cli.main', '_remove_custom_provider'),
    'main_u__getattr__': ('hermes_cli.main', '__getattr__'),
    'main_u_set_reasoning_effort': ('hermes_cli.main', '_set_reasoning_effort'),
    'main_u_prompt_reasoning_effort_selection': ('hermes_cli.main', '_prompt_reasoning_effort_selection'),
    'main_u_run_anthropic_oauth_flow': ('hermes_cli.main', '_run_anthropic_oauth_flow'),
    'main_cmd_login': ('hermes_cli.main', 'cmd_login'),
    'main_cmd_logout': ('hermes_cli.main', 'cmd_logout'),
    'main_cmd_slack': ('hermes_cli.main', 'cmd_slack'),
    'main_cmd_project': ('hermes_cli.main', 'cmd_project'),
    'main_cmd_hooks': ('hermes_cli.main', 'cmd_hooks'),
    'main_cmd_security': ('hermes_cli.main', 'cmd_security'),
    'main_cmd_import': ('hermes_cli.main', 'cmd_import'),
    'main_u_print_version_info': ('hermes_cli.main', '_print_version_info'),
    'main_cmd_version': ('hermes_cli.main', 'cmd_version'),
    'main_u_clear_bytecode_cache': ('hermes_cli.main', '_clear_bytecode_cache'),
    'main_u_capture_head_sha': ('hermes_cli.main', '_capture_head_sha'),
    'main_u_validate_critical_files_syntax': ('hermes_cli.main', '_validate_critical_files_syntax'),
    'main_u_gateway_prompt': ('hermes_cli.main', '_gateway_prompt'),
    'main_u_web_ui_build_needed': ('hermes_cli.main', '_web_ui_build_needed'),
    'main_u_compute_web_ui_content_hash': ('hermes_cli.main', '_compute_web_ui_content_hash'),
    'main_u_web_ui_stamp_path': ('hermes_cli.main', '_web_ui_stamp_path'),
    'main_u_write_web_ui_build_stamp': ('hermes_cli.main', '_write_web_ui_build_stamp'),
    'main_u_run_with_idle_timeout': ('hermes_cli.main', '_run_with_idle_timeout'),
    'main_u_nixos_build_env': ('hermes_cli.main', '_nixos_build_env'),
    'main_u_run_npm_install_deterministic': ('hermes_cli.main', '_run_npm_install_deterministic'),
    'main_u_build_web_ui': ('hermes_cli.main', '_build_web_ui'),
    'main_u_do_build_web_ui': ('hermes_cli.main', '_do_build_web_ui'),
    'main_u_desktop_dist_exists': ('hermes_cli.main', '_desktop_dist_exists'),
    'main_u_compute_desktop_content_hash': ('hermes_cli.main', '_compute_desktop_content_hash'),
    'main_u_desktop_stamp_path': ('hermes_cli.main', '_desktop_stamp_path'),
    'main_u_desktop_build_needed': ('hermes_cli.main', '_desktop_build_needed'),
    'main_u_write_desktop_build_stamp': ('hermes_cli.main', '_write_desktop_build_stamp'),
    'main_u_desktop_packaged_executable': ('hermes_cli.main', '_desktop_packaged_executable'),
    'main_u_expected_windows_pe_machines': ('hermes_cli.main', '_expected_windows_pe_machines'),
    'main_u_parse_pe_machine': ('hermes_cli.main', '_parse_pe_machine'),
    'main_u_pe_machine_or_none': ('hermes_cli.main', '_pe_machine_or_none'),
    'main_u_desktop_exe_integrity_error': ('hermes_cli.main', '_desktop_exe_integrity_error'),
    'main_u_desktop_backup_unpacked_dir': ('hermes_cli.main', '_desktop_backup_unpacked_dir'),
    'main_u_rollback_desktop_from_backup': ('hermes_cli.main', '_rollback_desktop_from_backup'),
    'main_u_ensure_desktop_exe_launchable': ('hermes_cli.main', '_ensure_desktop_exe_launchable'),
    'main_u_purge_electron_build_cache': ('hermes_cli.main', '_purge_electron_build_cache'),
    'main_u_redownload_electron_dist': ('hermes_cli.main', '_redownload_electron_dist'),
    'main_u_stop_desktop_processes_locking_build': ('hermes_cli.main', '_stop_desktop_processes_locking_build'),
    'main_u_desktop_macos_relaunchable_fixup': ('hermes_cli.main', '_desktop_macos_relaunchable_fixup'),
    'main_u_force_adhoc_macos_signing': ('hermes_cli.main', '_force_adhoc_macos_signing'),
    'main_u_desktop_linux_needs_no_sandbox': ('hermes_cli.main', '_desktop_linux_needs_no_sandbox'),
    'main_u_desktop_linux_sandbox_helper_is_regular_file': ('hermes_cli.main', '_desktop_linux_sandbox_helper_is_regular_file'),
    'main_u_desktop_linux_sandbox_fixup': ('hermes_cli.main', '_desktop_linux_sandbox_fixup'),
    'main_u_desktop_launch_options': ('hermes_cli.main', '_desktop_launch_options'),
    'main_cmd_gui': ('hermes_cli.main', 'cmd_gui'),
    'main_u_find_stale_dashboard_pids': ('hermes_cli.main', '_find_stale_dashboard_pids'),
    'main_u_print_curator_first_run_notice': ('hermes_cli.main', '_print_curator_first_run_notice'),
    'main_u_print_fts_optimize_available_notice': ('hermes_cli.main', '_print_fts_optimize_available_notice'),
    'main_u_print_curator_recent_run_notice': ('hermes_cli.main', '_print_curator_recent_run_notice'),
    'main_u_restart_managed_dashboard_service': ('hermes_cli.main', '_restart_managed_dashboard_service'),
    'main_u_kill_stale_dashboard_processes': ('hermes_cli.main', '_kill_stale_dashboard_processes'),
    'main_u_update_via_zip': ('hermes_cli.main', '_update_via_zip'),
    'main_u_stash_local_changes_if_needed': ('hermes_cli.main', '_stash_local_changes_if_needed'),
    'main_u_resolve_stash_selector': ('hermes_cli.main', '_resolve_stash_selector'),
    'main_u_print_stash_cleanup_guidance': ('hermes_cli.main', '_print_stash_cleanup_guidance'),
    'main_u_stash_apply_failed_only_on_existing_untracked': ('hermes_cli.main', '_stash_apply_failed_only_on_existing_untracked'),
    'main_u_restore_stashed_changes': ('hermes_cli.main', '_restore_stashed_changes'),
    'main_u_discard_stashed_changes': ('hermes_cli.main', '_discard_stashed_changes'),
    'main_u_get_origin_url': ('hermes_cli.main', '_get_origin_url'),
    'main_u_is_fork': ('hermes_cli.main', '_is_fork'),
    'main_u_has_upstream_remote': ('hermes_cli.main', '_has_upstream_remote'),
    'main_u_add_upstream_remote': ('hermes_cli.main', '_add_upstream_remote'),
    'main_u_count_commits_between': ('hermes_cli.main', '_count_commits_between'),
    'main_u_should_skip_upstream_prompt': ('hermes_cli.main', '_should_skip_upstream_prompt'),
    'main_u_mark_skip_upstream_prompt': ('hermes_cli.main', '_mark_skip_upstream_prompt'),
    'main_u_sync_fork_with_upstream': ('hermes_cli.main', '_sync_fork_with_upstream'),
    'main_u_sync_with_upstream_if_needed': ('hermes_cli.main', '_sync_with_upstream_if_needed'),
    'main_u_invalidate_update_cache': ('hermes_cli.main', '_invalidate_update_cache'),
    'main_u_load_installable_optional_extras': ('hermes_cli.main', '_load_installable_optional_extras'),
    'main_u_lazy_refresh_marker_path': ('hermes_cli.main', '_lazy_refresh_marker_path'),
    'main_u_write_marker_file': ('hermes_cli.main', '_write_marker_file'),
    'main_u_clear_marker_file': ('hermes_cli.main', '_clear_marker_file'),
    'main_u_write_update_incomplete_marker': ('hermes_cli.main', '_write_update_incomplete_marker'),
    'main_u_clear_update_incomplete_marker': ('hermes_cli.main', '_clear_update_incomplete_marker'),
    'main_u_write_lazy_refresh_incomplete_marker': ('hermes_cli.main', '_write_lazy_refresh_incomplete_marker'),
    'main_u_clear_lazy_refresh_incomplete_marker': ('hermes_cli.main', '_clear_lazy_refresh_incomplete_marker'),
    'main_u_recover_from_interrupted_install': ('hermes_cli.main', '_recover_from_interrupted_install'),
    'main_u_recover_lazy_refresh_marker_locked': ('hermes_cli.main', '_recover_lazy_refresh_marker_locked'),
    'main_u_recover_core_update_marker_locked': ('hermes_cli.main', '_recover_core_update_marker_locked'),
    'main_u_windows_running_hermes_launcher_locked': ('hermes_cli.main', '_windows_running_hermes_launcher_locked'),
    'main_u_default_venv_install_target': ('hermes_cli.main', '_default_venv_install_target'),
    'main_u_run_install_with_heartbeat': ('hermes_cli.main', '_run_install_with_heartbeat'),
    'main_u_venv_scripts_dir': ('hermes_cli.main', '_venv_scripts_dir'),
    'main_u_hermes_exe_shims': ('hermes_cli.main', '_hermes_exe_shims'),
    'main_u_detect_concurrent_hermes_instances': ('hermes_cli.main', '_detect_concurrent_hermes_instances'),
    'main_u_format_concurrent_instances_message': ('hermes_cli.main', '_format_concurrent_instances_message'),
    'main_u_quarantine_running_hermes_exe': ('hermes_cli.main', '_quarantine_running_hermes_exe'),
    'main_u_schedule_replace_on_reboot': ('hermes_cli.main', '_schedule_replace_on_reboot'),
    'main_u_restore_quarantined_exes': ('hermes_cli.main', '_restore_quarantined_exes'),
    'main_u_run_quarantined_install': ('hermes_cli.main', '_run_quarantined_install'),
    'main_u_cleanup_quarantined_exes': ('hermes_cli.main', '_cleanup_quarantined_exes'),
    'main_u_run_package_only_install': ('hermes_cli.main', '_run_package_only_install'),
    'main_u_lazy_refresh_repair_specs': ('hermes_cli.main', '_lazy_refresh_repair_specs'),
    'main_u_upgrade_pip_before_lazy_refresh': ('hermes_cli.main', '_upgrade_pip_before_lazy_refresh'),
    'main_u_detect_broken_lazy_refresh_imports': ('hermes_cli.main', '_detect_broken_lazy_refresh_imports'),
    'main_u_repair_broken_lazy_refresh_imports': ('hermes_cli.main', '_repair_broken_lazy_refresh_imports'),
    'main_u_repair_venv_via_import_probes': ('hermes_cli.main', '_repair_venv_via_import_probes'),
    'main_u_refresh_active_lazy_features': ('hermes_cli.main', '_refresh_active_lazy_features'),
    'main_u_install_python_dependencies_with_optional_fallback': ('hermes_cli.main', '_install_python_dependencies_with_optional_fallback'),
    'main_u_load_console_script_names': ('hermes_cli.main', '_load_console_script_names'),
    'main_u_verify_console_scripts_installed': ('hermes_cli.main', '_verify_console_scripts_installed'),
    'main_u_verify_core_dependencies_installed': ('hermes_cli.main', '_verify_core_dependencies_installed'),
    'main_u_resolve_install_target_python': ('hermes_cli.main', '_resolve_install_target_python'),
    'main_u_install_psutil_android_compat': ('hermes_cli.main', '_install_psutil_android_compat'),
    'main_u_ensure_uv_for_termux': ('hermes_cli.main', '_ensure_uv_for_termux'),
    'main_u_npm_manifest_paths': ('hermes_cli.main', '_npm_manifest_paths'),
    'main_u_npm_manifests_digest': ('hermes_cli.main', '_npm_manifests_digest'),
    'main_u_npm_lockfile_changed': ('hermes_cli.main', '_npm_lockfile_changed'),
    'main_u_record_npm_lockfile_hash': ('hermes_cli.main', '_record_npm_lockfile_hash'),
    'main_u_is_windows_npm_path': ('hermes_cli.main', '_is_windows_npm_path'),
    'main_u_resolve_node_runtime_npm': ('hermes_cli.main', '_resolve_node_runtime_npm'),
    'main_u_update_node_dependencies': ('hermes_cli.main', '_update_node_dependencies'),
    'main_u__getattr___2': ('hermes_cli.main', '__getattr__'),
    'main_u_install_hangup_protection': ('hermes_cli.main', '_install_hangup_protection'),
    'main_u_log_only_write': ('hermes_cli.main', '_log_only_write'),
    'main_u_run_logged_subprocess': ('hermes_cli.main', '_run_logged_subprocess'),
    'main_u_finalize_update_output': ('hermes_cli.main', '_finalize_update_output'),
    'main_u_resolve_update_branch': ('hermes_cli.main', '_resolve_update_branch'),
    'main_u_cmd_update_check': ('hermes_cli.main', '_cmd_update_check'),
    'main_u_ensure_fhs_path_guard': ('hermes_cli.main', '_ensure_fhs_path_guard'),
    'main_u_size_delta_label': ('hermes_cli.main', '_size_delta_label'),
    'main_u_resolve_pre_update_backup_mode': ('hermes_cli.main', '_resolve_pre_update_backup_mode'),
    'main_u_run_pre_update_backup': ('hermes_cli.main', '_run_pre_update_backup'),
    'main_u_write_update_planned_stop_marker': ('hermes_cli.main', '_write_update_planned_stop_marker'),
    'main_u_wait_for_windows_update_gateway_exit': ('hermes_cli.main', '_wait_for_windows_update_gateway_exit'),
    'main_u_venv_core_imports_healthy': ('hermes_cli.main', '_venv_core_imports_healthy'),
    'main_u_detect_venv_python_processes': ('hermes_cli.main', '_detect_venv_python_processes'),
    'main_u_format_venv_python_holders_message': ('hermes_cli.main', '_format_venv_python_holders_message'),
    'main_u_pause_windows_gateways_for_update': ('hermes_cli.main', '_pause_windows_gateways_for_update'),
    'main_u_cold_start_windows_gateway_after_update': ('hermes_cli.main', '_cold_start_windows_gateway_after_update'),
    'main_u_for_each_systemd_gateway_unit': ('hermes_cli.main', '_for_each_systemd_gateway_unit'),
    'main_u_warn_incomplete_gateway_fleet_restart': ('hermes_cli.main', '_warn_incomplete_gateway_fleet_restart'),
    'main_u_resume_windows_gateways_after_update': ('hermes_cli.main', '_resume_windows_gateways_after_update'),
    'main_u_discard_lockfile_churn': ('hermes_cli.main', '_discard_lockfile_churn'),
    'main_u_cmd_update_impl': ('hermes_cli.main', '_cmd_update_impl'),
    'main_u_render_distribution_plan': ('hermes_cli.main', '_render_distribution_plan'),
    'main_u_report_dashboard_status': ('hermes_cli.main', '_report_dashboard_status'),
    'main_u_dashboard_listening': ('hermes_cli.main', '_dashboard_listening'),
    'main_u_maybe_setup_dashboard_auth_interactively': ('hermes_cli.main', '_maybe_setup_dashboard_auth_interactively'),
    'main_u_read_ssh_session_token_file': ('hermes_cli.main', '_read_ssh_session_token_file'),
    'main_u_is_electron_packaged_web_dist': ('hermes_cli.main', '_is_electron_packaged_web_dist'),
    'main_cmd_dashboard_register': ('hermes_cli.main', 'cmd_dashboard_register'),
    'main_cmd_gateway_enroll': ('hermes_cli.main', 'cmd_gateway_enroll'),
    'main_cmd_completion': ('hermes_cli.main', 'cmd_completion'),
    'main_cmd_console': ('hermes_cli.main', 'cmd_console'),
    'main_u_plugin_cli_discovery_needed': ('hermes_cli.main', '_plugin_cli_discovery_needed'),
    'main_u_command_has_dedicated_mcp_startup': ('hermes_cli.main', '_command_has_dedicated_mcp_startup'),
    'main_u_should_background_mcp_startup': ('hermes_cli.main', '_should_background_mcp_startup'),
    'main_u_prepare_agent_startup': ('hermes_cli.main', '_prepare_agent_startup'),
    'main_u_apply_safe_mode': ('hermes_cli.main', '_apply_safe_mode'),
    'main_u_set_chat_arg_defaults': ('hermes_cli.main', '_set_chat_arg_defaults'),
    'main_u_try_termux_fast_cli_launch': ('hermes_cli.main', '_try_termux_fast_cli_launch'),
    'main_u_try_termux_fast_tui_launch': ('hermes_cli.main', '_try_termux_fast_tui_launch'),
    'main_cmd_acp': ('hermes_cli.main', 'cmd_acp'),
    'main_cmd_pairing': ('hermes_cli.main', 'cmd_pairing'),
    'main_cmd_claw': ('hermes_cli.main', 'cmd_claw'),
}

def main():
    if len(sys.argv) < 2: sys.stderr.write("usage: sta_oracle_port_main_wrappers.py <cases.json>\n"); return 2
    with open(sys.argv[1], 'r', encoding='utf-8') as f: cases = json.load(f)
    for c in cases:
        op = c.get('op'); value = c.get('value', '')
        d = DISPATCH.get(op)
        if not d: sys.stdout.write(json.dumps({'fn':op}, separators=(',',':')) + '\n'); continue
        pymod, pyfn = d
        mod = MODS.get(pymod)
        try:
            out = getattr(mod, pyfn)(value) if mod else None
        except Exception as e:
            out = 'PYERR:' + str(e)
        if isinstance(out, bool): out = bool(out)
        elif isinstance(out, (int, float)) and not isinstance(out, bool): out = int(out)
        elif out is None: out = ''
        else: out = str(out)
        sys.stdout.write(json.dumps({'fn':op,'out':out}, ensure_ascii=True, separators=(',',':')) + '\n')
    return 0

if __name__ == '__main__':
    sys.exit(main())
