"""AUTO-GENERATED integration oracle for port_gateway_run_wrappers (gen_integration_oracle.py)."""
import os, sys, json, importlib.util

MODS = {}
def _load(rel):
    _repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if _repo not in sys.path: sys.path.insert(0, _repo)
    for base in sys.path:
        cand = os.path.join(base, rel)
        try:
            spec = importlib.util.spec_from_file_location('live_' + rel.replace('/', '_').replace('.', '_'), cand)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            return mod
        except Exception:
            continue
    return None
MODS['gateway.run'] = _load('gateway/run.py')

DISPATCH = {
    'grun_u_send_or_update_status_coro': ('gateway.run', '_send_or_update_status_coro'),
    'grun_u_resolve_runtime_agent_kwargs': ('gateway.run', '_resolve_runtime_agent_kwargs'),
    'grun_u_resolve_runtime_agent_kwargs_for_provider': ('gateway.run', '_resolve_runtime_agent_kwargs_for_provider'),
    'grun_u_try_resolve_fallback_provider': ('gateway.run', '_try_resolve_fallback_provider'),
    'grun_u_probe_audio_duration': ('gateway.run', '_probe_audio_duration'),
    'grun_u_dequeue_pending_event': ('gateway.run', '_dequeue_pending_event'),
    'grun_u_get_channel_override': ('gateway.run', '_get_channel_override'),
    'grun_u_drain_gateway_watch_events': ('gateway.run', '_drain_gateway_watch_events'),
    'grun_u_dispose_unused_adapter': ('gateway.run', '_dispose_unused_adapter'),
    'grun_u_wire_teams_pipeline_runtime': ('gateway.run', '_wire_teams_pipeline_runtime'),
    'grun_u_warn_if_docker_media_delivery_is_risky': ('gateway.run', '_warn_if_docker_media_delivery_is_risky'),
    'grun_u_set_adapter_auto_tts_disabled': ('gateway.run', '_set_adapter_auto_tts_disabled'),
    'grun_u_set_adapter_auto_tts_enabled': ('gateway.run', '_set_adapter_auto_tts_enabled'),
    'grun_u_sync_voice_mode_state_to_adapter': ('gateway.run', '_sync_voice_mode_state_to_adapter'),
    'grun_u_await_adapter_cleanup_with_timeout': ('gateway.run', '_await_adapter_cleanup_with_timeout'),
    'grun_u_safe_adapter_disconnect': ('gateway.run', '_safe_adapter_disconnect'),
    'grun_u_bounded_adapter_teardown': ('gateway.run', '_bounded_adapter_teardown'),
    'grun_u_connect_initial_adapter_with_timeout': ('gateway.run', '_connect_initial_adapter_with_timeout'),
    'grun_u_telegram_topic_mode_enabled': ('gateway.run', '_telegram_topic_mode_enabled'),
    'grun_u_should_send_telegram_lobby_reminder': ('gateway.run', '_should_send_telegram_lobby_reminder'),
    'grun_u_record_telegram_topic_binding': ('gateway.run', '_record_telegram_topic_binding'),
    'grun_u_sync_telegram_topic_binding': ('gateway.run', '_sync_telegram_topic_binding'),
    'grun_u_recover_telegram_topic_thread_id': ('gateway.run', '_recover_telegram_topic_thread_id'),
    'grun_u_normalize_source_for_session_key': ('gateway.run', '_normalize_source_for_session_key'),
    'grun_u_resolve_session_agent_runtime': ('gateway.run', '_resolve_session_agent_runtime'),
    'grun_u_resolve_turn_agent_config': ('gateway.run', '_resolve_turn_agent_config'),
    'grun_u_sync_session_model_from_agent': ('gateway.run', '_sync_session_model_from_agent'),
    'grun_u_handle_reaction_event': ('gateway.run', '_handle_reaction_event'),
    'grun_u_handle_adapter_fatal_error': ('gateway.run', '_handle_adapter_fatal_error'),
    'grun_u_handle_adapter_fatal_error_detached': ('gateway.run', '_handle_adapter_fatal_error_detached'),
    'grun_u_handle_adapter_fatal_error_impl': ('gateway.run', '_handle_adapter_fatal_error_impl'),
    'grun_u_restart_loop_guard_config': ('gateway.run', '_restart_loop_guard_config'),
    'grun_u_log_scale_to_zero_not_armed_reason': ('gateway.run', '_log_scale_to_zero_not_armed_reason'),
    'grun_u_scale_to_zero_note_real_inbound': ('gateway.run', '_scale_to_zero_note_real_inbound'),
    'grun_u_relay_adapter_for_dormancy': ('gateway.run', '_relay_adapter_for_dormancy'),
    'grun_u_scale_to_zero_watcher': ('gateway.run', '_scale_to_zero_watcher'),
    'grun_u_enqueue_fifo': ('gateway.run', '_enqueue_fifo'),
    'grun_u_promote_queued_event': ('gateway.run', '_promote_queued_event'),
    'grun_u_clear_goal_pending_continuations': ('gateway.run', '_clear_goal_pending_continuations'),
    'grun_u_persist_active_agents': ('gateway.run', '_persist_active_agents'),
    'grun_u_enter_external_drain': ('gateway.run', '_enter_external_drain'),
    'grun_u_exit_external_drain': ('gateway.run', '_exit_external_drain'),
    'grun_u_drain_control_watcher': ('gateway.run', '_drain_control_watcher'),
    'grun_u_pause_failed_platform': ('gateway.run', '_pause_failed_platform'),
    'grun_u_resume_paused_platform': ('gateway.run', '_resume_paused_platform'),
    'grun_u_resolve_model_for_channel': ('gateway.run', '_resolve_model_for_channel'),
    'grun_u_get_system_prompt_for_channel': ('gateway.run', '_get_system_prompt_for_channel'),
    'grun_u_refresh_fallback_model': ('gateway.run', '_refresh_fallback_model'),
    'grun_u_apply_fallback_chain_to_agent': ('gateway.run', '_apply_fallback_chain_to_agent'),
    'grun_u_snapshot_running_agents': ('gateway.run', '_snapshot_running_agents'),
    'grun_u_claim_active_session_slot': ('gateway.run', '_claim_active_session_slot'),
    'grun_u_agent_has_active_subagents': ('gateway.run', '_agent_has_active_subagents'),
    'grun_u_session_has_compression_in_flight': ('gateway.run', '_session_has_compression_in_flight'),
    'grun_u_lookup_session_id_under_store_lock': ('gateway.run', '_lookup_session_id_under_store_lock'),
    'grun_u_queue_or_replace_pending_event': ('gateway.run', '_queue_or_replace_pending_event'),
    'grun_u_handle_active_session_busy_message': ('gateway.run', '_handle_active_session_busy_message'),
    'grun_u_notify_active_sessions_of_shutdown': ('gateway.run', '_notify_active_sessions_of_shutdown'),
    'grun_u_finalize_shutdown_agents': ('gateway.run', '_finalize_shutdown_agents'),
    'grun_u_should_emit_long_running_notification': ('gateway.run', '_should_emit_long_running_notification'),
    'grun_u_defer_agent_cleanup_until_future_done': ('gateway.run', '_defer_agent_cleanup_until_future_done'),
    'grun_u_cleanup_agent_resources_off_loop': ('gateway.run', '_cleanup_agent_resources_off_loop'),
    'grun_u_cleanup_agent_resources': ('gateway.run', '_cleanup_agent_resources'),
    'grun_u_increment_restart_failure_counts': ('gateway.run', '_increment_restart_failure_counts'),
    'grun_u_suspend_stuck_loop_sessions': ('gateway.run', '_suspend_stuck_loop_sessions'),
    'grun_u_launch_detached_restart_command': ('gateway.run', '_launch_detached_restart_command'),
    'grun_u_run_startup_resume_event': ('gateway.run', '_run_startup_resume_event'),
    'grun_u_queue_startup_restore_event': ('gateway.run', '_queue_startup_restore_event'),
    'grun_u_drain_startup_restore_queue': ('gateway.run', '_drain_startup_restore_queue'),
    'grun_u_finish_startup_restore': ('gateway.run', '_finish_startup_restore'),
    'grun_u_redeliver_pending_obligations': ('gateway.run', '_redeliver_pending_obligations'),
    'grun_u_schedule_resume_pending_sessions': ('gateway.run', '_schedule_resume_pending_sessions'),
    'grun_u_abort_startup_if_shutdown_requested': ('gateway.run', '_abort_startup_if_shutdown_requested'),
    'grun_u_start_loop_liveness_guards': ('gateway.run', '_start_loop_liveness_guards'),
    'grun_u_stop_loop_liveness_guards': ('gateway.run', '_stop_loop_liveness_guards'),
    'grun_u_spawn_supervised': ('gateway.run', '_spawn_supervised'),
    'grun_u_handoff_watcher': ('gateway.run', '_handoff_watcher'),
    'grun_u_process_handoff': ('gateway.run', '_process_handoff'),
    'grun_u_session_expiry_watcher': ('gateway.run', '_session_expiry_watcher'),
    'grun_u_ensure_reconnect_watcher_running': ('gateway.run', '_ensure_reconnect_watcher_running'),
    'grun_u_platform_reconnect_watcher': ('gateway.run', '_platform_reconnect_watcher'),
    'grun_u_cancel_secondary_profile_reconnect_tasks': ('gateway.run', '_cancel_secondary_profile_reconnect_tasks'),
    'grun_u_start_systemd_watchdog': ('gateway.run', '_start_systemd_watchdog'),
    'grun_u_stop_systemd_watchdog': ('gateway.run', '_stop_systemd_watchdog'),
    'grun_u_start_secondary_profile_adapters': ('gateway.run', '_start_secondary_profile_adapters'),
    'grun_u_start_one_profile_adapters': ('gateway.run', '_start_one_profile_adapters'),
    'grun_u_configure_profile_adapter': ('gateway.run', '_configure_profile_adapter'),
    'grun_u_run_secondary_profile_reconnect': ('gateway.run', '_run_secondary_profile_reconnect'),
    'grun_u_schedule_secondary_profile_reconnect': ('gateway.run', '_schedule_secondary_profile_reconnect'),
    'grun_u_make_profile_fatal_error_handler': ('gateway.run', '_make_profile_fatal_error_handler'),
    'grun_u_handle_profile_adapter_fatal_error': ('gateway.run', '_handle_profile_adapter_fatal_error'),
    'grun_u_make_profile_message_handler': ('gateway.run', '_make_profile_message_handler'),
    'grun_u_create_adapter': ('gateway.run', '_create_adapter'),
    'grun_u_make_adapter_auth_check': ('gateway.run', '_make_adapter_auth_check'),
    'grun_u_deliver_platform_notice': ('gateway.run', '_deliver_platform_notice'),
    'grun_u_resolve_async_delegation_session': ('gateway.run', '_resolve_async_delegation_session'),
    'grun_u_prepare_inbound_message_text': ('gateway.run', '_prepare_inbound_message_text'),
    'grun_u_prepare_profile_scoped_inbound_message_text': ('gateway.run', '_prepare_profile_scoped_inbound_message_text'),
    'grun_async_session_store': ('gateway.run', 'async_session_store'),
    'grun_u_handle_message_with_agent': ('gateway.run', '_handle_message_with_agent'),
    'grun_u_reset_notice_session_info': ('gateway.run', '_reset_notice_session_info'),
    'grun_u_format_session_info': ('gateway.run', '_format_session_info'),
    'grun_u_sibling_thread_run_keys': ('gateway.run', '_sibling_thread_run_keys'),
    'grun_u_is_stale_restart_redelivery': ('gateway.run', '_is_stale_restart_redelivery'),
    'grun_u_handle_suggestions_command': ('gateway.run', '_handle_suggestions_command'),
    'grun_u_handle_blueprint_command': ('gateway.run', '_handle_blueprint_command'),
    'grun_u_get_goal_manager_for_event': ('gateway.run', '_get_goal_manager_for_event'),
    'grun_u_send_goal_status_notice': ('gateway.run', '_send_goal_status_notice'),
    'grun_u_defer_goal_status_notice_after_delivery': ('gateway.run', '_defer_goal_status_notice_after_delivery'),
    'grun_u_post_turn_goal_continuation': ('gateway.run', '_post_turn_goal_continuation'),
    'grun_u_handle_voice_channel_join': ('gateway.run', '_handle_voice_channel_join'),
    'grun_u_handle_voice_channel_leave': ('gateway.run', '_handle_voice_channel_leave'),
    'grun_u_handle_voice_timeout_cleanup': ('gateway.run', '_handle_voice_timeout_cleanup'),
    'grun_u_handle_voice_channel_input': ('gateway.run', '_handle_voice_channel_input'),
    'grun_u_should_send_voice_reply': ('gateway.run', '_should_send_voice_reply'),
    'grun_u_send_voice_reply': ('gateway.run', '_send_voice_reply'),
    'grun_u_deliver_media_from_response': ('gateway.run', '_deliver_media_from_response'),
    'grun_u_run_background_task': ('gateway.run', '_run_background_task'),
    'grun_u_run_background_task_inner': ('gateway.run', '_run_background_task_inner'),
    'grun_u_get_telegram_topic_capabilities': ('gateway.run', '_get_telegram_topic_capabilities'),
    'grun_u_ensure_telegram_system_topic': ('gateway.run', '_ensure_telegram_system_topic'),
    'grun_u_send_telegram_topic_setup_image': ('gateway.run', '_send_telegram_topic_setup_image'),
    'grun_u_rename_discord_auto_thread_for_session_title': ('gateway.run', '_rename_discord_auto_thread_for_session_title'),
    'grun_u_schedule_discord_semantic_thread_rename': ('gateway.run', '_schedule_discord_semantic_thread_rename'),
    'grun_u_rename_telegram_topic_for_session_title': ('gateway.run', '_rename_telegram_topic_for_session_title'),
    'grun_u_schedule_telegram_topic_title_rename': ('gateway.run', '_schedule_telegram_topic_title_rename'),
    'grun_u_disable_telegram_topic_mode_for_chat': ('gateway.run', '_disable_telegram_topic_mode_for_chat'),
    'grun_u_telegram_topic_root_status_message': ('gateway.run', '_telegram_topic_root_status_message'),
    'grun_u_restore_telegram_topic_session': ('gateway.run', '_restore_telegram_topic_session'),
    'grun_u_execute_mcp_reload': ('gateway.run', '_execute_mcp_reload'),
    'grun_u_maybe_confirm_destructive_slash': ('gateway.run', '_maybe_confirm_destructive_slash'),
    'grun_u_request_slash_confirm': ('gateway.run', '_request_slash_confirm'),
    'grun_u_read_user_config': ('gateway.run', '_read_user_config'),
    'grun_u_schedule_update_notification_watch': ('gateway.run', '_schedule_update_notification_watch'),
    'grun_u_watch_update_progress': ('gateway.run', '_watch_update_progress'),
    'grun_u_send_update_notification': ('gateway.run', '_send_update_notification'),
    'grun_u_send_restart_notification': ('gateway.run', '_send_restart_notification'),
    'grun_u_send_home_channel_startup_notifications': ('gateway.run', '_send_home_channel_startup_notifications'),
    'grun_u_set_session_env': ('gateway.run', '_set_session_env'),
    'grun_u_clear_session_env': ('gateway.run', '_clear_session_env'),
    'grun_u_run_in_executor_with_context': ('gateway.run', '_run_in_executor_with_context'),
    'grun_u_get_executor': ('gateway.run', '_get_executor'),
    'grun_u_shutdown_executor': ('gateway.run', '_shutdown_executor'),
    'grun_u_enrich_message_with_vision': ('gateway.run', '_enrich_message_with_vision'),
    'grun_u_enrich_message_with_transcription': ('gateway.run', '_enrich_message_with_transcription'),
    'grun_u_pending_event_audio_paths': ('gateway.run', '_pending_event_audio_paths'),
    'grun_u_transcribe_pending_audio_event_once': ('gateway.run', '_transcribe_pending_audio_event_once'),
    'grun_u_echo_pending_stt_transcripts_once': ('gateway.run', '_echo_pending_stt_transcripts_once'),
    'grun_u_transcribe_and_echo_pending_voice': ('gateway.run', '_transcribe_and_echo_pending_voice'),
    'grun_u_build_process_event_source': ('gateway.run', '_build_process_event_source'),
    'grun_u_inject_watch_notification': ('gateway.run', '_inject_watch_notification'),
    'grun_u_classify_completion_target': ('gateway.run', '_classify_completion_target'),
    'grun_u_deliver_completion_notification': ('gateway.run', '_deliver_completion_notification'),
    'grun_u_enrich_async_delegation_routing': ('gateway.run', '_enrich_async_delegation_routing'),
    'grun_u_async_delegation_watcher': ('gateway.run', '_async_delegation_watcher'),
    'grun_u_run_process_watcher': ('gateway.run', '_run_process_watcher'),
    'grun_u_extract_honcho_cache_busting_config': ('gateway.run', '_extract_honcho_cache_busting_config'),
    'grun_u_extract_cache_busting_config': ('gateway.run', '_extract_cache_busting_config'),
    'grun_u_agent_config_signature': ('gateway.run', '_agent_config_signature'),
    'grun_u_rehydrate_session_model_override': ('gateway.run', '_rehydrate_session_model_override'),
    'grun_u_release_running_agent_state': ('gateway.run', '_release_running_agent_state'),
    'grun_u_release_turn_lease': ('gateway.run', '_release_turn_lease'),
    'grun_u_rebind_turn_lease': ('gateway.run', '_rebind_turn_lease'),
    'grun_u_clear_conversation_scope': ('gateway.run', '_clear_conversation_scope'),
    'grun_u_clear_session_boundary_security_state': ('gateway.run', '_clear_session_boundary_security_state'),
    'grun_u_bind_adapter_run_generation': ('gateway.run', '_bind_adapter_run_generation'),
    'grun_u_interrupt_and_clear_session': ('gateway.run', '_interrupt_and_clear_session'),
    'grun_u_refresh_agent_cache_message_count': ('gateway.run', '_refresh_agent_cache_message_count'),
    'grun_u_voice_channel_sidecar_note': ('gateway.run', '_voice_channel_sidecar_note'),
    'grun_u_pinned_session_context_prompt': ('gateway.run', '_pinned_session_context_prompt'),
    'grun_u_init_cached_agent_for_turn': ('gateway.run', '_init_cached_agent_for_turn'),
    'grun_u_commit_memory_before_soft_evict': ('gateway.run', '_commit_memory_before_soft_evict'),
    'grun_u_commit_then_release_soft': ('gateway.run', '_commit_then_release_soft'),
    'grun_u_release_evicted_agent_soft': ('gateway.run', '_release_evicted_agent_soft'),
    'grun_u_enforce_agent_cache_cap': ('gateway.run', '_enforce_agent_cache_cap'),
    'grun_u_sweep_idle_cached_agents': ('gateway.run', '_sweep_idle_cached_agents'),
    'grun_u_run_agent_via_proxy': ('gateway.run', '_run_agent_via_proxy'),
    'grun_u_profile_name_for_source': ('gateway.run', '_profile_name_for_source'),
    'grun_u_resolve_profile_home_for_source': ('gateway.run', '_resolve_profile_home_for_source'),
    'grun_u_run_planned_stop_watcher': ('gateway.run', '_run_planned_stop_watcher'),
    'grun_u_start_gateway_housekeeping': ('gateway.run', '_start_gateway_housekeeping'),
    'grun_u_start_cron_ticker': ('gateway.run', '_start_cron_ticker'),
    'grun_u_await_thread_exit': ('gateway.run', '_await_thread_exit'),
    'grun_start_gateway': ('gateway.run', 'start_gateway'),
    'grun_u_exit_after_graceful_shutdown': ('gateway.run', '_exit_after_graceful_shutdown'),
}

def main():
    if len(sys.argv) < 2: sys.stderr.write("usage: sta_oracle_port_gateway_run_wrappers.py <cases.json>\n"); return 2
    with open(sys.argv[1], 'r', encoding='utf-8') as f: cases = json.load(f)
    for c in cases:
        op = c.get('op'); value = c.get('value', '')
        d = DISPATCH.get(op)
        if not d: sys.stdout.write(json.dumps({'fn':op}, separators=(',',':')) + '\n'); continue
        pymod, pyfn = d
        mod = MODS.get(pymod)
        try:
            out = getattr(mod, pyfn)(value) if mod else None
        except Exception as e:
            out = 'PYERR:' + str(e)
        if isinstance(out, bool): out = bool(out)
        elif isinstance(out, (int, float)) and not isinstance(out, bool): out = int(out)
        elif out is None: out = ''
        else: out = str(out)
        sys.stdout.write(json.dumps({'fn':op,'out':out}, ensure_ascii=True, separators=(',',':')) + '\n')
    return 0

if __name__ == '__main__':
    sys.exit(main())
