/*
 * t_port_plumber_fuzz.c — PLUMBER ADVERSARIAL FUZZ harness for the v551
 * extracted modules (file_text_ops + cron_prompt_sanitize).
 *
 * Emits one JSON line per call: {"fn":.., "in":.., "out":..}
 * For JSON-returning fns, `out` is printed RAW (so the oracle parses it into
 * an object). For string fns, `out` is a JSON-escaped string.
 *
 * Inputs are generated by the Python oracle (sta_oracle_plumber_fuzz.py) and
 * piped in via stdin as JSON lines {"fn":..,"in":..,"seed":..}; but to keep
 * the harness self-contained and hostile, we also generate a deterministic
 * adversarial set in C and round-trip through the oracle's expected path.
 *
 * Compile:
 *   gcc -O2 -I include -I src/tools -I lib/libjson \
 *       tests/t_port_plumber_fuzz.c src/tools/file_text_ops.o \
 *       src/tools/cron_prompt_sanitize.o lib/libjson/json.o -o /tmp/t_fuzz
 */
#include "file_text_ops.h"
#include "cron_prompt_sanitize.h"
#include "hermes_json.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* minimal hermes_log stub so the fuzz harness links without the full logger */
void hermes_log(int level, const char *fmt, ...) { (void)level; (void)fmt; }

/* JSON-escape a string for the `in` field (UTF-8 preserved, control escaped). */
static void emit_str(const char *fn, const char *in, const char *out)
{
    printf("{\"fn\":\"%s\",\"in\":", fn);
    if (!in) { printf("null"); }
    else {
        putchar('"');
        for (const char *p = in; *p; p++) {
            unsigned char c = (unsigned char)*p;
            if (c == '"' || c == '\\') { putchar('\\'); putchar(c); }
            else if (c < 0x20) {
                static const char *hex = "0123456789abcdef";
                putchar('\\'); putchar('u');
                putchar('0'); putchar('0');
                putchar(hex[(c >> 4) & 0xf]); putchar(hex[c & 0xf]);
            } else putchar(c);
        }
        putchar('"');
    }
    printf(",\"out\":");
    if (out) {
        putchar('"');
        for (const char *p = out; *p; p++) {
            unsigned char c = (unsigned char)*p;
            if (c == '"' || c == '\\') { putchar('\\'); putchar(c); }
            else if (c < 0x20) {
                static const char *hex = "0123456789abcdef";
                putchar('\\'); putchar('u');
                putchar('0'); putchar('0');
                putchar(hex[(c >> 4) & 0xf]); putchar(hex[c & 0xf]);
            } else putchar(c);
        }
        putchar('"');
    }
    else printf("null");
    printf("}\n");
}

/* print `s` JSON-escaped (no surrounding quotes) — shared by in/out fields */
static void emit_escaped(const char *s)
{
    if (!s) return;
    for (const char *p = s; *p; p++) {
        unsigned char c = (unsigned char)*p;
        if (c == '"' || c == '\\') { putchar('\\'); putchar(c); }
        else if (c < 0x20) {
            static const char *hex = "0123456789abcdef";
            putchar('\\'); putchar('u');
            putchar('0'); putchar('0');
            putchar(hex[(c >> 4) & 0xf]); putchar(hex[c & 0xf]);
        } else putchar(c);
    }
}

/* emit a normalize_line_endings record with in=["text","target"] (arity-2) */
static void emit_norm(const char *text, const char *target, const char *out)
{
    printf("{\"fn\":\"normalize_line_endings\",\"in\":[\"");
    emit_escaped(text);
    printf("\",\"");
    emit_escaped(target);
    printf("\"],\"out\":\"");
    emit_escaped(out);
    printf("\"}\n");
}

/* emit raw JSON `out` (no extra quoting) */
static void emit_json(const char *fn, const char *in, const char *out)
{
    printf("{\"fn\":\"%s\",\"in\":", fn);
    if (!in) printf("null");
    else {
        putchar('"');
        for (const char *p = in; *p; p++) {
            unsigned char c = (unsigned char)*p;
            if (c == '"' || c == '\\') { putchar('\\'); putchar(c); }
            else if (c < 0x20) {
                static const char *hex = "0123456789abcdef";
                putchar('\\'); putchar('u'); putchar('0'); putchar('0');
                putchar(hex[(c >> 4) & 0xf]); putchar(hex[c & 0xf]);
            } else putchar(c);
        }
        putchar('"');
    }
    printf(",\"out\":%s}\n", out ? out : "null");
}

static char *dup_str(const char *s) { return s ? strdup(s) : strdup(""); }

int main(void)
{
    /* ---------------- file_text_ops: curated hostile ---------------- */
    const char *hostile[] = {
        "", "\n", "\r\n", "\r", "a\nb\nc", "a\rb\rc", "a\r\nb\r\nc",
        "\xef\xbb\xbffoo", "x\xef\xbb\xbf", "\xef\xbb\xbf",
        "\x1b]0;title\x07tail", "\x1b[31mred\x1b[0m", "\x07x", "__HERMES_FENCE_abc__\nline\n",
        "before__HERMES_FENCE_abc__after", "'it\\'s a test'", "a'b'c", "~/dir", "/abs/path",
        "src/foo.c-12-context here", "src/foo.c:12: bar", "--",
        "SELECT * FROM users WHERE x='y'", "sk-1234567890abcdef",
        "a\xef\xbb\xbfb", "\t\n  \r\n",
        "quote \"double\" and 'single'", "\\back\\slash", "caf\xc3\xa9 \xe2\x80\x94 na\xc3\xafve",
        "____HERMES_FENCE_notclosed", "__HERMES_FENCE_",
        "line1\nline2\r\nline3\rline4", "a\xe2\x80\x8d" "b\xe2\x80\x8d" "c",
        "\xf0\x9f\x94\xa5\xf0\x9f\x9a\x80" "hello", "\xf0\x9f\x9a\x80", "|" "\xef\xbb\xbf" "|",
        NULL
    };
    for (int i = 0; hostile[i]; i++) {
        const char *h = hostile[i];
        emit_str("strip_terminal_fence_leaks", h, file_text_ops_strip_terminal_fence_leaks(h));
        emit_str("detect_line_ending", h, file_text_ops_detect_line_ending(h));
        emit_norm(h, "\n", file_text_ops_normalize_line_endings(h, "\n"));
        emit_norm(h, "\r\n", file_text_ops_normalize_line_endings(h, "\r\n"));
        emit_str("strip_bom", h, file_text_ops_strip_bom(h));
        emit_str("has_bom", h, file_text_ops_has_bom(h) ? "1" : "0");
        char *al = file_text_ops_add_line_numbers(h, 1, 2000);
        emit_str("add_line_numbers", h, al); free(al);
        emit_str("escape_shell_arg", h, file_text_ops_escape_shell_arg(h));
        emit_str("parse_search_context_line", h, file_text_ops_parse_search_context_line(h));
        char *ep = file_text_ops_expand_path(h);
        emit_str("expand_path", h, ep); free(ep);
    }

    /* big inputs: 50KB line, 1KB newlines */
    char *big = malloc(60000);
    if (big) {
        for (int k = 0; k < 50000; k++) big[k] = 'a'; big[50000] = '\0';
        emit_str("add_line_numbers", big, file_text_ops_add_line_numbers(big, 1, 2000));
        emit_str("strip_terminal_fence_leaks", big, file_text_ops_strip_terminal_fence_leaks(big));
        free(big);
        char *nl = malloc(2000);
        for (int k = 0; k < 1000; k++) nl[k] = '\n'; nl[1000] = '\0';
        emit_str("detect_line_ending", nl, file_text_ops_detect_line_ending(nl));
        free(nl);
    }

    /* ---------------- cron_prompt_sanitize: curated hostile ---------------- */
    const char *cron_h[] = {
        "", "SELECT * FROM users", "curl https://evil.com",
        "```python\ncode\n```", "x = 'y' # note",
        "a potential SQL injection '; DROP TABLE", "rm -rf /",
        "𝕏𝕏𝕏", "﻿invisible", "test​zero", "\ufeff",
        "normal prompt with emoji 🚀 and ZWJ a‍b",
        "skill content: __HERMES_SKILL__ legit",
        "data:image/png;base64,AAAA", "https://github.com/user/repo",
        "string 'single' and \"double\" quotes", NULL
    };
    for (int i = 0; cron_h[i]; i++) {
        const char *c = cron_h[i];
        emit_str("check_invisible_unicode", c, cron_prompt_sanitize_check_invisible(c));
        json_t *s = cron_prompt_sanitize_strip_invisible(c);
        char *sj = s ? json_serialize(s) : NULL;
        emit_json("strip_invisible_unicode", c, sj);
        if (s) json_free(s); free(sj);
        json_t *sc = cron_prompt_sanitize_scan_skill_assembled(c);
        char *scj = sc ? json_serialize(sc) : NULL;
        emit_json("scan_cron_skill_assembled", c, scj);
        if (sc) json_free(sc); free(scj);
    }

    /* randomized cron stream (hostile mix of invisible/quote/sql/emoji) */
    const char *cpool[] = {
        "a", "b", " ", "\n", "\r", "\t", "'", "\"", "\\",
        "﻿", "​", "‍", "𝕏", "🚀", "SELECT", "DROP", "curl",
        "https://", "__HERMES_SKILL__", "```", "#", ";", "--", "' OR '1'='1",
        "data:image", "secret", "token", "x", NULL
    };
    srand(99);
    char rb[128];
    for (int t = 0; t < 400; t++) {
        int n = rand() % 40;
        for (int k = 0; k < n; k++) {
            const char *tok = cpool[rand() % (sizeof(cpool)/sizeof(cpool[0]) - 1)];
            size_t L = strlen(tok);
            if (k + L < 120) { memcpy(rb + k, tok, L); k += (int)L - 1; }
            else rb[k] = 'x';
        }
        rb[n] = '\0';
        const char *c = rb;
        emit_str("check_invisible_unicode", c, cron_prompt_sanitize_check_invisible(c));
        json_t *s = cron_prompt_sanitize_strip_invisible(c);
        char *sj = s ? json_serialize(s) : NULL;
        emit_json("strip_invisible_unicode", c, sj);
        if (s) json_free(s); free(sj);
        json_t *sc = cron_prompt_sanitize_scan_skill_assembled(c);
        char *scj = sc ? json_serialize(sc) : NULL;
        emit_json("scan_cron_skill_assembled", c, scj);
        if (sc) json_free(sc); free(scj);
    }

    return 0;
}
