/* ================================================================
 * i18n.c — Lightweight internationalization.
 * Port of Python agent/i18n.py (258 lines).
 *
 * Uses embedded locale data (generated by i18n_data.inc).
 * MIT License — WuBu Slermes Project
 * ================================================================ */

#include "hermes_i18n.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdarg.h>

/* Embedded locale data */
/* Port of Python: _flatten_into — arch diff: C data pre-flattened via i18n_data.inc, no runtime YAML parsing */
#include "i18n_data.inc"

/* ================================================================
 *  Language aliases
 * ================================================================ */
/* AG26: Port of Python agent/i18n.py:resolve_alias(). */
static const char *resolve_alias(const char *lang)
{
    if (!lang || !*lang) return NULL;
    struct { const char *alias; const char *canonical; } aliases[] = {
        {"english", "en"}, {"en-us", "en"}, {"en-gb", "en"},
        {"chinese", "zh"}, {"mandarin", "zh"}, {"zh-cn", "zh"},
        {"zh-hans", "zh"}, {"zh-sg", "zh"},
        {"traditional-chinese", "zh-hant"}, {"traditional_chinese", "zh-hant"},
        {"zh-tw", "zh-hant"}, {"zh-hk", "zh-hant"}, {"zh-mo", "zh-hant"},
        {"japanese", "ja"}, {"jp", "ja"}, {"ja-jp", "ja"},
        {"german", "de"}, {"deutsch", "de"}, {"de-de", "de"},
        {"spanish", "es"}, {"es-es", "es"},
        {"french", "fr"}, {"fr-fr", "fr"},
        {"ukrainian", "uk"}, {"uk-ua", "uk"}, {"ua", "uk"},
        {"turkish", "tr"}, {"tr-tr", "tr"},
        {"korean", "ko"}, {"ko-kr", "ko"},
        {"italian", "it"}, {"it-it", "it"},
        {"portuguese", "pt"}, {"pt-pt", "pt"}, {"pt-br", "pt"},
        {"russian", "ru"}, {"ru-ru", "ru"},
        {"hungarian", "hu"}, {"hu-hu", "hu"},
        {"afrikaans", "af"}, {"af-za", "af"},
        {"irish", "ga"}, {"ga-ie", "ga"},
        {NULL, NULL}
    };

    char lower[64];
    size_t i = 0;
    while (lang[i] && i < sizeof(lower) - 1) {
        lower[i] = (char)tolower((unsigned char)lang[i]);
        i++;
    }
    lower[i] = '\0';

    for (int a = 0; aliases[a].alias; a++)
        if (strcmp(lower, aliases[a].alias) == 0)
            return aliases[a].canonical;

    /* Strip region suffix */
    const char *dash = strchr(lower, '-');
    if (dash) {
        size_t base_len = (size_t)(dash - lower);
        for (int a = 0; aliases[a].alias; a++)
            if (strncmp(lower, aliases[a].alias, base_len) == 0 &&
                strlen(aliases[a].alias) == base_len)
                return aliases[a].canonical;
    }
    return NULL;
}

static bool is_supported(const char *lang)
{
    for (int i = 0; i < _i18n_catalog_count; i++)
        if (strcmp(lang, _i18n_catalogs[i].lang) == 0)
            return true;
    return false;
}

/* Port of Python: _normalize_lang */
static const char *normalize_lang(const char *input)
{
    if (!input || !*input) return "en";
    if (is_supported(input)) return input;
    const char *alias = resolve_alias(input);
    if (alias) return alias;
    return "en";
}

/* ================================================================
 *  Find catalog / lookup key
 * ================================================================ */

/* Port of Python: _load_catalog */
static const i18n_catalog_t *find_catalog(const char *lang)
{
    if (!lang) return NULL;
    for (int i = 0; i < _i18n_catalog_count; i++)
        if (strcmp(lang, _i18n_catalogs[i].lang) == 0)
            return &_i18n_catalogs[i];
    return NULL;
}

/* Port of Python hermes_cli/web_server.py:_catalog_lookup(). */
/* Linear scan through the sorted entries (sentinel-terminated) */
static const char *catalog_lookup(const i18n_catalog_t *cat, const char *key)
{
    if (!cat || !key) return NULL;
    for (size_t i = 0; i < cat->count; i++) {
        if (cat->entries[i].key[0] == '\0') break; /* sentinel */
        if (strcmp(cat->entries[i].key, key) == 0)
            return cat->entries[i].value;
    }
    return NULL;
}

/* ================================================================
 *  Format string with {placeholder} substitution
 * ================================================================ */

static char *format_string(const char *template, const i18n_arg_t *args, size_t nargs)
{
    if (!template) return strdup("");

    size_t tlen = strlen(template);
    size_t out_size = tlen + 4096;
    char *out = (char *)malloc(out_size);
    if (!out) return NULL;

    const char *p = template;
    size_t pos = 0;

    while (*p && pos < out_size - 1) {
        if (*p == '{') {
            const char *end = strchr(p + 1, '}');
            if (end) {
                size_t klen = (size_t)(end - p - 1);
                const char *key = p + 1;
                bool found = false;

                for (size_t a = 0; a < nargs; a++) {
                    if (strlen(args[a].key) == klen &&
                        strncmp(args[a].key, key, klen) == 0) {
                        const char *val = args[a].value ? args[a].value : "";
                        size_t vlen = strlen(val);
                        if (pos + vlen < out_size - 1) {
                            memcpy(out + pos, val, vlen);
                            pos += vlen;
                        }
                        found = true;
                        break;
                    }
                }

                if (!found) {
                    size_t clen = klen + 2;
                    if (pos + clen < out_size - 1) {
                        memcpy(out + pos, p, clen);
                        pos += clen;
                    }
                }
                p = end + 1;
            } else {
                out[pos++] = *p++;
            }
        } else {
            out[pos++] = *p++;
        }
    }
    out[pos] = '\0';
    return out;
}

/* ================================================================
 *  Public API — simplified: all data is embedded
 * ================================================================ */

/* Port of Python: _locales_dir (C embeds data, path not needed) */
int i18n_init(const char *locales_path)
{
    (void)locales_path;
    /* Embedded catalogs are loaded at compile time via i18n_data.inc.
     * No runtime directory resolution needed — just verify catalog count. */
    if (_i18n_catalog_count <= 0) {
        return -1;
    }
    return _i18n_catalog_count;
}

void i18n_set_locales_dir(const char *path)
{
    (void)path; /* Not used with embedded data */
}

/* Port of Python: get_language — also covers _config_language_cached (C reads getenv directly, no config.yaml fallback) */
/* AG26: Port of Python agent/i18n.py:_config_language_cached() */
const char *get_language(void)
{
    const char *env = getenv("HERMES_LANGUAGE");
    if (env && *env) return normalize_lang(env);
    return "en";
}

/* Port of Python: t */
char *i18n_t(const char *key)
{
    return i18n_t_lang_vfmt(key, NULL, NULL, 0);
}

char *i18n_t_lang(const char *key, const char *lang)
{
    return i18n_t_lang_vfmt(key, lang, NULL, 0);
}

char *i18n_t_fmt(const char *key, ...)
{
    i18n_arg_t args[I18N_MAX_ARGS];
    size_t nargs = 0;
    va_list ap;
    va_start(ap, key);
    const char *arg_key = va_arg(ap, const char *);
    while (arg_key && nargs < I18N_MAX_ARGS) {
        args[nargs].key = arg_key;
        args[nargs].value = va_arg(ap, const char *);
        nargs++;
        arg_key = va_arg(ap, const char *);
    }
    va_end(ap);
    return i18n_t_vfmt(key, args, nargs);
}

char *i18n_t_vfmt(const char *key, const i18n_arg_t *args, size_t nargs)
{
    return i18n_t_lang_vfmt(key, NULL, args, nargs);
}

char *i18n_t_lang_vfmt(const char *key, const char *lang,
                        const i18n_arg_t *args, size_t nargs)
{
    if (!key) return strdup("");

    const char *target = lang ? normalize_lang(lang) : get_language();

    const i18n_catalog_t *cat = find_catalog(target);
    const char *value = cat ? catalog_lookup(cat, key) : NULL;

    /* Fall back to English */
    if (!value && strcmp(target, "en") != 0) {
        cat = find_catalog("en");
        value = cat ? catalog_lookup(cat, key) : NULL;
    }

    if (!value) return strdup(key);

    if (args && nargs > 0)
        return format_string(value, args, nargs);

    return strdup(value);
}

/* Port of Python: reset_language_cache */
void reset_language_cache(void)
{
    /* Nothing to free — data is static */
}

void i18n_cleanup(void)
{
    reset_language_cache();
}
