/*
 * flux3_video_tool.c — Additional helper ports from tools/flux3_video_tool.py.
 *
 * The 8 helpers already ported by port_tools_flux3_video.c
 * (_looks_like_local_path, _display_path, _filename_from_url,
 * _is_transport_error, _poll_is_finished, _retry_after_seconds,
 * _without_media, _submit_args) are NOT duplicated here.
 *
 * This file adds: _resolve_destination, _free_path, _still_generating.
 */
#define _GNU_SOURCE
#include "flux3_video_tool.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <sys/stat.h>
#include <ctype.h>

#include "managed_gateway.h"
#include "tool_backend.h"
#include "port_auth_store.h"  /* get_provider_auth_state */
#include "hermes_billing.h"  /* peek/read_nous_access_token */
#include "hermes_gateway_session_context.h"  /* gw_session_is_messaging_surface */
#include "slermes_home.h"  /* slermes_home */

/* Vendor name for BFL gateway routes (PoP: _VENDOR @ tools/flux3_video_tool.py:_VENDOR) */

/* PoP: _still_generating @ tools/flux3_video_tool.py:_still_generating */
char *flux3_still_generating(const char *job_id)
{
    char *out = NULL;
    if (!job_id) return NULL;
    /* Python uses em dash (U+2014, UTF-8 E2 80 94) not hyphen */
    asprintf(&out,
        "{\"result\": \"Still generating. This call reached its own time limit, "
        "which the job is unaffected by \xe2\x80\x94 call bfl_flux3_get_result again with "
        "id=%s to keep waiting.\", \"details\": {\"id\": \"%s\", \"status\": \"Generating\"}}",
        job_id, job_id);
    return out;
}

/* PoP: _resolve_destination @ tools/flux3_video_tool.py:_resolve_destination */
char *flux3_resolve_destination(const char *save_to, const char *filename)
{
    if (!filename) filename = "flux3-video.mp4";
    char dir[4096];
    if (save_to && *save_to) {
        strncpy(dir, save_to, sizeof(dir) - 1);
        dir[sizeof(dir) - 1] = '\0';
        size_t len = strlen(dir);
        while (len > 0 && (dir[len-1] == '/' || dir[len-1] == '\\'))
            dir[--len] = '\0';
        struct stat st;
        if (stat(dir, &st) != 0 || !S_ISDIR(st.st_mode)) {
            return strdup(save_to);
        }
    } else {
        /* Python: directory, name = _default_directory(), filename */
        char *dd = flux3_default_directory();
        if (dd) {
            strncpy(dir, dd, sizeof(dir) - 1);
            dir[sizeof(dir) - 1] = '\0';
            free(dd);
        } else {
            strcpy(dir, ".");
        }
    }
    return flux3_free_path(dir, filename);
}

/* PoP: _free_path @ tools/flux3_video_tool.py:_free_path */
char *flux3_free_path(const char *directory, const char *name)
{
    char candidate[4096];
    snprintf(candidate, sizeof(candidate), "%s/%s", directory ? directory : ".",
             name ? name : "flux3-video.mp4");
    struct stat st;
    if (stat(candidate, &st) != 0)
        return strdup(candidate);

    const char *dot = strrchr(name, '.');
    const char *base = strrchr(name, '/');
    if (base) base++;
    else base = name;
    char stem[256], suffix[32];
    if (dot && dot > base) {
        size_t sl = (size_t)(dot - base);
        if (sl >= sizeof(stem)) sl = sizeof(stem) - 1;
        memcpy(stem, base, sl); stem[sl] = '\0';
        size_t suf_l = strlen(dot);
        if (suf_l >= sizeof(suffix)) suf_l = sizeof(suffix) - 1;
        memcpy(suffix, dot, suf_l); suffix[suf_l] = '\0';
    } else {
        strncpy(stem, base, sizeof(stem) - 1);
        stem[sizeof(stem) - 1] = '\0';
        strcpy(suffix, "");
    }
    for (int s = 2; s < FLUX3_MAX_FILENAME_ATTEMPTS + 2; s++) {
        snprintf(candidate, sizeof(candidate), "%s/%s-%d%s", directory, stem, s, suffix);
        if (stat(candidate, &st) != 0) return strdup(candidate);
    }
    return NULL;
}

/* PoP: _shared_submit_properties @ tools/flux3_video_tool.py:_shared_submit_properties */
json_t *flux3_shared_submit_properties(void)
{
    json_t *props = json_object();

    json_t *prompt = json_object();
    json_set(prompt, "type", json_string("string"));
    json_set(prompt, "minLength", json_number(1));
    json_set(prompt, "description", json_string(
        "Generation brief in plain prose (it is interpreted and expanded by a reasoning "
        "harness). Order it subject, distinguishing visual specifics, action, camera, "
        "lighting, environment, audio, style. Audio is generated by default \xe2\x80\x94 say "
        "\"no music\" if unwanted."));
    json_set(props, "prompt", prompt);

    json_t *aspect = json_object();
    json_set(aspect, "type", json_string("string"));
    json_t *ar = json_array();
    const char *ratios[] = {"auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16", "9:21"};
    for (int i = 0; i < 8; i++) json_append(ar, json_string(ratios[i]));
    json_set(aspect, "enum", ar);
    json_set(aspect, "default", json_string("auto"));
    json_set(aspect, "description", json_string("Output aspect ratio. \"auto\" lets the model choose."));
    json_set(props, "aspect_ratio", aspect);

    json_t *dur = json_object();
    json_t *one = json_array();
    json_t *i1 = json_object();
    json_set(i1, "type", json_string("integer"));
    json_set(i1, "minimum", json_number(5));
    json_set(i1, "maximum", json_number(20));
    json_append(one, i1);
    json_t *i2 = json_object();
    json_set(i2, "type", json_string("string"));
    json_set(i2, "const", json_string("auto"));
    json_append(one, i2);
    json_set(dur, "oneOf", one);
    json_set(dur, "default", json_string("auto"));
    json_set(dur, "description", json_string("Clip duration in whole seconds (5-20), or \"auto\"."));
    json_set(props, "duration", dur);

    json_t *res = json_object();
    json_set(res, "type", json_string("string"));
    json_t *ra = json_array();
    json_append(ra, json_string("720p"));
    json_set(res, "enum", ra);
    json_set(res, "default", json_string("720p"));
    json_set(res, "description", json_string("Output resolution bin."));
    json_set(props, "resolution", res);

    json_t *ga = json_object();
    json_set(ga, "type", json_string("boolean"));
    json_set(ga, "default", json_bool(true));
    json_set(ga, "description", json_string("Generate synchronized audio."));
    json_set(props, "generate_audio", ga);

    json_t *gr = json_object();
    json_set(gr, "type", json_string("boolean"));
    json_set(gr, "default", json_bool(true));
    json_set(gr, "description", json_string("Allow a short research pass before generation."));
    json_set(props, "grounding", gr);

    json_t *sd = json_object();
    json_set(sd, "type", json_string("integer"));
    json_set(sd, "minimum", json_number(0));
    json_set(sd, "maximum", json_number(4294967295));
    json_set(sd, "description", json_string("Optional reproducibility seed."));
    json_set(props, "seed", sd);

    json_t *ver = json_object();
    json_set(ver, "type", json_string("string"));
    json_set(ver, "description", json_string("Model version pin. Defaults to \"latest\"."));
    json_set(props, "version", ver);
    return props;
}

/* PoP: _endpoints @ tools/flux3_video_tool.py:_endpoints */
/* Python: return managed_vendor_endpoints(_VENDOR)  ("bfl"). */
/* Delegates to managed_gateway lib. Returns NULL when unreachable. */
json_t *flux3_endpoints(void)
{
    char base_url[512], upload_path[512];
    if (managed_vendor_endpoints(NULL, "bfl", base_url, sizeof(base_url),
                                 upload_path, sizeof(upload_path)) != 0)
        return NULL;
    char *r = json_object();
        char origin[GW_URL_MAX];
        managed_gw_build_url("tool", origin, sizeof(origin));
        json_set(r, "origin", json_string(origin));
        json_set(r, "base_url", json_string(base_url));
        /* Python managed_vendor_endpoints returns upload_path as the
         * RELATIVE path (managed_vendor_upload_path), not the full URL. */
        json_set(r, "upload_path", json_string(upload_path));
        return r;
}

/* PoP: _warm_nous_token @ tools/flux3_video_tool.py:_warm_nous_token */
/* Python: read_nous_access_token() with exception swallowed. Delegates to
 * the already-ported managed_tool_gateway read_nous_access_token wrapper. */
void flux3_warm_nous_token(void)
{
    char tok[2048];
    /* Returns 0 on success, -1 when no token. Python swallows on exception. */
    (void)cli_tools_managed_tool_gateway_read_nous_access_token(tok, sizeof(tok));
}

/* PoP: _has_nous_credential @ tools/flux3_video_tool.py:_has_nous_credential */
/* Faithful to Python: True if peek_nous_access_token() succeeds OR if
 * get_provider_auth_state("nous") has a non-empty access_token. */
bool flux3_has_nous_credential(void)
{
    char tok[2048];
    if (cli_tools_managed_tool_gateway_peek_nous_access_token(tok, sizeof(tok)) == 0 && tok[0])
        return true;
    json_t *state = get_provider_auth_state("nous");
    if (!state) return false;
    json_t *token = json_obj_get(state, "access_token");
    bool r = false;
    if (token && token->type == JSON_STRING && token->str_val && token->str_val[0]) {
        /* Check strip() equivalent: non-whitespace content */
        const char *s = token->str_val;
        for (const char *p = s; *p; p++) {
            if (!isspace((unsigned char)*p)) { r = true; break; }
        }
    }
    json_free(state);
    return r;
}

/* PoP: check_bfl_requirements @ tools/flux3_video_tool.py:check_bfl_requirements */
/* True if _endpoints() resolves AND _has_nous_credential(). */
bool flux3_check_bfl_requirements(void)
{
    json_t *ep = flux3_endpoints();
    if (!ep) return false;
    json_free(ep);
    return flux3_has_nous_credential();
}

/* PoP: _delivers_as_an_attachment @ tools/flux3_video_tool.py:_delivers_as_an_attachment */
bool flux3_delivers_as_an_attachment(void)
{
    return gw_session_is_messaging_surface();
}

/* PoP: _default_directory @ tools/flux3_video_tool.py:_default_directory */
char *flux3_default_directory(void)
{
    if (gw_session_is_messaging_surface()) {
        const char *h = slermes_home();
        if (h && *h) {
            char buf[4096];
            snprintf(buf, sizeof(buf), "%s/cache/videos", h);
            return strdup(buf);
        }
    }
    /* Non-messaging: Downloads/ if exists, else cwd. */
    const char *home = getenv("HOME");
    if (home) {
        char dl[4096];
        snprintf(dl, sizeof(dl), "%s/Downloads", home);
        struct stat st;
        if (stat(dl, &st) == 0 && S_ISDIR(st.st_mode))
            return strdup(dl);
    }
    return strdup(".");
}
