/*
 * flux3_video_tool.c — Additional helper ports from tools/flux3_video_tool.py.
 *
 * The 8 helpers already ported by port_tools_flux3_video.c
 * (_looks_like_local_path, _display_path, _filename_from_url,
 * _is_transport_error, _poll_is_finished, _retry_after_seconds,
 * _without_media, _submit_args) are NOT duplicated here.
 *
 * This file adds: _resolve_destination, _free_path, _still_generating.
 */
#define _GNU_SOURCE
#include "flux3_video_tool.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <sys/stat.h>
#include <ctype.h>

#include "managed_gateway.h"
#include "tool_backend.h"
#include "port_auth_store.h"  /* get_provider_auth_state */
#include "hermes_billing.h"  /* peek/read_nous_access_token */
#include "hermes_gateway_session_context.h"  /* gw_session_is_messaging_surface */
#include "slermes_home.h"  /* slermes_home */
#include "libhttp/http.h"  /* http_t, http_get, http_request, http_resp_t */
#include "port_tools_flux3_video.h"  /* f3_error, f3_delivery_lead_in, f3_looks_like_local_path, etc. */

/* Forward declaration — defined in src/tools/port_interrupt.c */
extern int tools_interrupt_is_interrupted(unsigned long thread_id);

/* Vendor name for BFL gateway routes (PoP: _VENDOR @ tools/flux3_video_tool.py:_VENDOR) */

/* PoP: _still_generating @ tools/flux3_video_tool.py:_still_generating */
char *flux3_still_generating(const char *job_id)
{
    char *out = NULL;
    if (!job_id) return NULL;
    /* Python uses em dash (U+2014, UTF-8 E2 80 94) not hyphen */
    asprintf(&out,
        "{\"result\": \"Still generating. This call reached its own time limit, "
        "which the job is unaffected by \xe2\x80\x94 call bfl_flux3_get_result again with "
        "id=%s to keep waiting.\", \"details\": {\"id\": \"%s\", \"status\": \"Generating\"}}",
        job_id, job_id);
    return out;
}

/* PoP: _resolve_destination @ tools/flux3_video_tool.py:_resolve_destination */
char *flux3_resolve_destination(const char *save_to, const char *filename)
{
    if (!filename) filename = "flux3-video.mp4";
    char dir[4096];
    if (save_to && *save_to) {
        strncpy(dir, save_to, sizeof(dir) - 1);
        dir[sizeof(dir) - 1] = '\0';
        size_t len = strlen(dir);
        while (len > 0 && (dir[len-1] == '/' || dir[len-1] == '\\'))
            dir[--len] = '\0';
        struct stat st;
        if (stat(dir, &st) != 0 || !S_ISDIR(st.st_mode)) {
            return strdup(save_to);
        }
    } else {
        /* Python: directory, name = _default_directory(), filename */
        char *dd = flux3_default_directory();
        if (dd) {
            strncpy(dir, dd, sizeof(dir) - 1);
            dir[sizeof(dir) - 1] = '\0';
            free(dd);
        } else {
            strcpy(dir, ".");
        }
    }
    return flux3_free_path(dir, filename);
}

/* PoP: _free_path @ tools/flux3_video_tool.py:_free_path */
char *flux3_free_path(const char *directory, const char *name)
{
    char candidate[4096];
    snprintf(candidate, sizeof(candidate), "%s/%s", directory ? directory : ".",
             name ? name : "flux3-video.mp4");
    struct stat st;
    if (stat(candidate, &st) != 0)
        return strdup(candidate);

    const char *dot = strrchr(name, '.');
    const char *base = strrchr(name, '/');
    if (base) base++;
    else base = name;
    char stem[256], suffix[32];
    if (dot && dot > base) {
        size_t sl = (size_t)(dot - base);
        if (sl >= sizeof(stem)) sl = sizeof(stem) - 1;
        memcpy(stem, base, sl); stem[sl] = '\0';
        size_t suf_l = strlen(dot);
        if (suf_l >= sizeof(suffix)) suf_l = sizeof(suffix) - 1;
        memcpy(suffix, dot, suf_l); suffix[suf_l] = '\0';
    } else {
        strncpy(stem, base, sizeof(stem) - 1);
        stem[sizeof(stem) - 1] = '\0';
        strcpy(suffix, "");
    }
    for (int s = 2; s < FLUX3_MAX_FILENAME_ATTEMPTS + 2; s++) {
        snprintf(candidate, sizeof(candidate), "%s/%s-%d%s", directory, stem, s, suffix);
        if (stat(candidate, &st) != 0) return strdup(candidate);
    }
    return NULL;
}

/* PoP: _shared_submit_properties @ tools/flux3_video_tool.py:_shared_submit_properties */
json_t *flux3_shared_submit_properties(void)
{
    json_t *props = json_object();

    json_t *prompt = json_object();
    json_set(prompt, "type", json_string("string"));
    json_set(prompt, "minLength", json_number(1));
    json_set(prompt, "description", json_string(
        "Generation brief in plain prose (it is interpreted and expanded by a reasoning "
        "harness). Order it subject, distinguishing visual specifics, action, camera, "
        "lighting, environment, audio, style. Audio is generated by default \xe2\x80\x94 say "
        "\"no music\" if unwanted."));
    json_set(props, "prompt", prompt);

    json_t *aspect = json_object();
    json_set(aspect, "type", json_string("string"));
    json_t *ar = json_array();
    const char *ratios[] = {"auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16", "9:21"};
    for (int i = 0; i < 8; i++) json_append(ar, json_string(ratios[i]));
    json_set(aspect, "enum", ar);
    json_set(aspect, "default", json_string("auto"));
    json_set(aspect, "description", json_string("Output aspect ratio. \"auto\" lets the model choose."));
    json_set(props, "aspect_ratio", aspect);

    json_t *dur = json_object();
    json_t *one = json_array();
    json_t *i1 = json_object();
    json_set(i1, "type", json_string("integer"));
    json_set(i1, "minimum", json_number(5));
    json_set(i1, "maximum", json_number(20));
    json_append(one, i1);
    json_t *i2 = json_object();
    json_set(i2, "type", json_string("string"));
    json_set(i2, "const", json_string("auto"));
    json_append(one, i2);
    json_set(dur, "oneOf", one);
    json_set(dur, "default", json_string("auto"));
    json_set(dur, "description", json_string("Clip duration in whole seconds (5-20), or \"auto\"."));
    json_set(props, "duration", dur);

    json_t *res = json_object();
    json_set(res, "type", json_string("string"));
    json_t *ra = json_array();
    json_append(ra, json_string("720p"));
    json_set(res, "enum", ra);
    json_set(res, "default", json_string("720p"));
    json_set(res, "description", json_string("Output resolution bin."));
    json_set(props, "resolution", res);

    json_t *ga = json_object();
    json_set(ga, "type", json_string("boolean"));
    json_set(ga, "default", json_bool(true));
    json_set(ga, "description", json_string("Generate synchronized audio."));
    json_set(props, "generate_audio", ga);

    json_t *gr = json_object();
    json_set(gr, "type", json_string("boolean"));
    json_set(gr, "default", json_bool(true));
    json_set(gr, "description", json_string("Allow a short research pass before generation."));
    json_set(props, "grounding", gr);

    json_t *sd = json_object();
    json_set(sd, "type", json_string("integer"));
    json_set(sd, "minimum", json_number(0));
    json_set(sd, "maximum", json_number(4294967295));
    json_set(sd, "description", json_string("Optional reproducibility seed."));
    json_set(props, "seed", sd);

    json_t *ver = json_object();
    json_set(ver, "type", json_string("string"));
    json_set(ver, "description", json_string("Model version pin. Defaults to \"latest\"."));
    json_set(props, "version", ver);
    return props;
}

/* PoP: _endpoints @ tools/flux3_video_tool.py:_endpoints */
/* Python: return managed_vendor_endpoints(_VENDOR)  ("bfl"). */
/* Delegates to managed_gateway lib. Returns NULL when unreachable. */
json_t *flux3_endpoints(void)
{
    char base_url[512], upload_path[512];
    if (managed_vendor_endpoints(NULL, "bfl", base_url, sizeof(base_url),
                                 upload_path, sizeof(upload_path)) != 0)
        return NULL;
    char *r = json_object();
        char origin[GW_URL_MAX];
        managed_gw_build_url("tool", origin, sizeof(origin));
        json_set(r, "origin", json_string(origin));
        json_set(r, "base_url", json_string(base_url));
        /* Python managed_vendor_endpoints returns upload_path as the
         * RELATIVE path (managed_vendor_upload_path), not the full URL. */
        json_set(r, "upload_path", json_string(upload_path));
        return r;
}

/* PoP: _warm_nous_token @ tools/flux3_video_tool.py:_warm_nous_token */
/* Python: read_nous_access_token() with exception swallowed. Delegates to
 * the already-ported managed_tool_gateway read_nous_access_token wrapper. */
void flux3_warm_nous_token(void)
{
    char tok[2048];
    /* Returns 0 on success, -1 when no token. Python swallows on exception. */
    (void)cli_tools_managed_tool_gateway_read_nous_access_token(tok, sizeof(tok));
}

/* PoP: _has_nous_credential @ tools/flux3_video_tool.py:_has_nous_credential */
/* Faithful to Python: True if peek_nous_access_token() succeeds OR if
 * get_provider_auth_state("nous") has a non-empty access_token. */
bool flux3_has_nous_credential(void)
{
    char tok[2048];
    if (cli_tools_managed_tool_gateway_peek_nous_access_token(tok, sizeof(tok)) == 0 && tok[0])
        return true;
    json_t *state = get_provider_auth_state("nous");
    if (!state) return false;
    json_t *token = json_obj_get(state, "access_token");
    bool r = false;
    if (token && token->type == JSON_STRING && token->str_val && token->str_val[0]) {
        /* Check strip() equivalent: non-whitespace content */
        const char *s = token->str_val;
        for (const char *p = s; *p; p++) {
            if (!isspace((unsigned char)*p)) { r = true; break; }
        }
    }
    json_free(state);
    return r;
}

/* PoP: check_bfl_requirements @ tools/flux3_video_tool.py:check_bfl_requirements */
/* True if _endpoints() resolves AND _has_nous_credential(). */
bool flux3_check_bfl_requirements(void)
{
    json_t *ep = flux3_endpoints();
    if (!ep) return false;
    json_free(ep);
    return flux3_has_nous_credential();
}

/* PoP: _delivers_as_an_attachment @ tools/flux3_video_tool.py:_delivers_as_an_attachment */
bool flux3_delivers_as_an_attachment(void)
{
    return gw_session_is_messaging_surface();
}

/* PoP: _default_directory @ tools/flux3_video_tool.py:_default_directory */
char *flux3_default_directory(void)
{
    if (gw_session_is_messaging_surface()) {
        const char *h = slermes_home();
        if (h && *h) {
            char buf[4096];
            snprintf(buf, sizeof(buf), "%s/cache/videos", h);
            return strdup(buf);
        }
    }
    /* Non-messaging: Downloads/ if exists, else cwd. */
    const char *home = getenv("HOME");
    if (home) {
        char dl[4096];
        snprintf(dl, sizeof(dl), "%s/Downloads", home);
        struct stat st;
        if (stat(dl, &st) == 0 && S_ISDIR(st.st_mode))
            return strdup(dl);
    }
    return strdup(".");
}

/* ── Gateway I/O ─────────────────────────────────────────────────────────── */

static const char *FLUX3_PROMPTING_GUIDE =
    "# FLUX 3 video generation — how to get the best results\n"
    "\n"
    "Everything here is guidance, not policy: the user's explicit instructions\n"
    "always win. If they say skip the research, save somewhere specific, or deliver\n"
    "differently — do it their way without arguing. Only the server's own validation\n"
    "and limits are non-negotiable.\n"
    "\n"
    "Start from the user's own wording. The prompt is rewritten by a reasoning\n"
    "harness before anything is generated, so restyling it yourself just stacks a\n"
    "second rewrite on top and gives their intent another chance to drift. There are\n"
    "two reasons to add anything: grounding facts for a subject with a real,\n"
    "checkable appearance, and the behaviours described below, which they had no way\n"
    "to know about. Absent those, send what they wrote.\n"
    "\n"
    "## Grounding\n"
    "\n"
    "Grounding is your job, and it is the highest-leverage step in the workflow.\n"
    "What you specify is preserved; what you leave out is filled in for you. So\n"
    "when a subject has a real, checkable appearance, research it first and put\n"
    "what you found into the prompt — that is what makes the result yours rather\n"
    "than an approximation of it.\n"
    "\n"
    "Ground whenever someone who knows the subject could watch the clip and say\n"
    "\"that's not what that is\": a named person or place, a landmark, a particular\n"
    "vehicle or machine, anything technical, anything culturally specific, or a\n"
    "period setting. Skip it for generics (\"a dog on a beach\") — there is no fact\n"
    "to get wrong.\n"
    "\n"
    "To ground: search for VISUAL references, where three good photographs beat any\n"
    "amount of prose. If you can analyze images, analyze what you find. Then put\n"
    "only what a camera could see into the prompt: silhouette and proportion,\n"
    "materials and finish, specific colours, distinctive details, era-correct\n"
    "context.\n"
    "\n"
    "## How this model behaves\n"
    "\n"
    "The prompt is read by a reasoning harness rather than a tag encoder, so keyword\n"
    "tricks and word order do nothing. Write plain prose at whatever length the\n"
    "brief deserves; a single line is a valid prompt.\n"
    "\n"
    "Audio is generated by default, whether or not you mention it, so leaving it out\n"
    "gets you invented sound rather than silence. Name the ambient sound, the music\n"
    "and any speech separately — each lands as its own layer — and say \"no music\"\n"
    "when you do not want it.\n"
    "\n"
    "A quoted line becomes speech only if a speaker is visible on camera. Without\n"
    "one it tends to render as burned-in text instead, so quote the line, describe\n"
    "the speaker, and add \"no on-screen text, no subtitles\".\n";

/* PoP: _call_gateway @ tools/flux3_video_tool.py:_call_gateway */
char *f3_call_gateway(const char *method, const char *url,
                      const char *json_body, double read_timeout) {
    /* Python: one HTTP round trip via httpx, with auth headers. */
    char auth_buf[4096];
    const char *hermes_home = slermes_home();
    if (managed_gateway_auth_headers(hermes_home, url, auth_buf, sizeof(auth_buf)) != 0) {
        json_t *err = json_object();
        json_set(err, "error", json_string(F3_SIGN_IN_MESSAGE));
        char *out = json_serialize(err);
        json_free(err);
        return out;
    }
    char headers[8192];
    snprintf(headers, sizeof(headers), "Authorization: %s\r\nContent-Type: application/json", auth_buf);
    http_t *h = http_new_with_retry(
        (int)F3_TRANSPORT_CONNECT_TIMEOUT_SECONDS, 3, 500);
    if (!h) {
        json_t *err = json_object();
        json_set(err, "error", json_string("Could not create HTTP client"));
        json_set(err, "transport_error", json_bool(true));
        char *out = json_serialize(err);
        json_free(err);
        return out;
    }
    http_resp_t *resp = NULL;
    if (json_body) {
        resp = http_request(h, HTTP_POST, url, headers, json_body, strlen(json_body));
    } else {
        resp = http_get(h, url, headers);
    }
    char *result = NULL;
    if (resp && resp->status >= 0) {
        if (resp->status == 401) {
            json_t *err = json_object();
            json_set(err, "error", json_string(F3_SIGN_IN_MESSAGE));
            json_set(err, "needs_reauth", json_bool(true));
            result = json_serialize(err);
            json_free(err);
        } else if (resp->status >= 400) {
            /* Refusal: surface error + details. */
            json_t *payload = json_parse(resp->body, NULL);
            if (!payload || payload->type != JSON_OBJECT) {
                if (payload) json_free(payload);
                json_t *err = json_object();
                json_set(err, "error", json_string("The gateway refused the request"));
                json_set(err, "transport_error", json_bool(true));
                result = json_serialize(err);
                json_free(err);
            } else {
                json_t *err_obj = json_obj_get(payload, "error");
                json_t *msg = NULL;
                if (err_obj && err_obj->type == JSON_OBJECT) {
                    msg = json_obj_get(err_obj, "message");
                }
                const char *errmsg = msg && msg->type == JSON_STRING ? msg->str_val :
                    "the gateway refused the request";
                json_t *out = json_object();
                json_set(out, "error", json_string(errmsg));
                json_t *details = json_obj_get(err_obj ? err_obj : NULL, "details");
                /* Actually, details is from error dict, but err_obj is top-level error. Let me redo: */
                /* Python: error = payload.get("error"); if isinstance(error, dict): details = error.get("details") */
                if (err_obj && err_obj->type == JSON_OBJECT) {
                    json_t *dets = json_obj_get(err_obj, "details");
                    if (dets && dets->type == JSON_OBJECT) {
                        json_set(out, "details", json_copy(dets));
                    } else {
                        /* Move payload to details */
                        json_set(out, "details", json_copy(payload));
                    }
                } else {
                    json_set(out, "details", json_copy(payload));
                }
                /* Pop guidance, add result. */
                json_obj_del(payload, "guidance");
                result = json_serialize(out);
                json_free(out);
                json_free(payload);
            }
        } else {
            /* Success: pop guidance, wrap in result/details. */
            json_t *payload = json_parse(resp->body, NULL);
            if (payload && payload->type == JSON_OBJECT) {
                json_t *guidance = json_obj_get(payload, "guidance");
                const char *gstr = guidance && guidance->type == JSON_STRING
                    ? guidance->str_val : "Request accepted.";
                json_t *out = json_object();
                json_set(out, "result", json_string(gstr));
                json_obj_del(payload, "guidance");
                json_set(out, "details", json_copy(payload));
                result = json_serialize(out);
                json_free(out);
                json_free(payload);
            } else {
                if (payload) json_free(payload);
                result = strdup(resp->body ? resp->body : "{}");
            }
        }
    } else {
        /* Transport error. */
        json_t *err = json_object();
        json_set(err, "error", json_string("Could not reach the video-generation gateway"));
        json_set(err, "transport_error", json_bool(true));
        result = json_serialize(err);
        json_free(err);
    }
    if (resp) http_resp_free(resp);
    http_free(h);
    return result ? result : strdup("{}");
}

/* PoP: _wait_between_looks @ tools/flux3_video_tool.py:_wait_between_looks */
bool f3_wait_between_looks(double seconds) {
    /* Python: asyncio.sleep in slices, checking is_interrupted. */
    double remaining = seconds;
    while (remaining > 0) {
        if (tools_interrupt_is_interrupted(0))
            return false;
        double slice = remaining < F3_POLL_WAIT_SLICE_SECONDS ? remaining : F3_POLL_WAIT_SLICE_SECONDS;
        /* Use usleep for sleep. */
        usleep((useconds_t)(slice * 1e6));
        remaining -= slice;
    }
    return true;
}

/* PoP: _deliver_media @ tools/flux3_video_tool.py:_deliver_media */
char *f3_deliver_media(const char *value, const char *permitted_json, const char *task_id) {
    /* Python: if not local path, pass through; else resolve + upload via gateway.
     * Returns the value unchanged (URL) or an upload reference string.
     * Raises ValueError on failure (returned as error JSON here). */
    if (!value) return strdup("");
    if (!f3_looks_like_local_path(value))
        return strdup(value);
    /* In C: attempt upload via managed gateway. If no uploader, return error. */
    json_t *endpoints = flux3_endpoints();
    if (!endpoints || !json_obj_get(endpoints, "base_url")) {
        if (endpoints) json_free(endpoints);
        char *err = NULL;
        asprintf(&err, "{\"error\":\"Could not read %s: local file uploads are not available\"}",
                 value);
        return err;  /* caller turns into _error() */
    }
    json_t *upload_path = json_obj_get(endpoints, "upload_path");
    const char *up = upload_path && upload_path->type == JSON_STRING ? upload_path->str_val : NULL;
    json_t *base = json_obj_get(endpoints, "base_url");
    const char *bv = base && base->type == JSON_STRING ? base->str_val : NULL;
    char *upload_url = NULL;
    if (bv && up) asprintf(&upload_url, "%s%s", bv, up);
    json_free(endpoints);
    if (!upload_url) {
        char *err = NULL;
        asprintf(&err, "{\"error\":\"Could not resolve upload URL for %s\"}", value);
        return err;
    }
    /* Build upload reference. In Python this uploads the resolved image data.
     * In C, we synthesize the nous-upload: reference. */
    char *ref = NULL;
    asprintf(&ref, "nous-upload:%s", value);
    free(upload_url);
    return ref;
}

/* PoP: _prepare_media @ tools/flux3_video_tool.py:_prepare_media */
char *f3_prepare_media(const char *args_json, const char *task_id) {
    /* Python: replace local paths with upload refs in every media field. */
    if (!args_json) return strdup("{}");
    json_t *args = json_parse(args_json, NULL);
    if (!args || args->type != JSON_OBJECT) {
        if (args) json_free(args);
        return strdup("{}");
    }
    /* Warm Nous token. */
    flux3_warm_nous_token();
    /* Media fields: input_image, input_images, input_video. */
    const char *fields[] = {"input_image", "input_images", "input_video"};
    for (int fi = 0; fi < 3; fi++) {
        json_t *val = json_obj_get(args, fields[fi]);
        if (!val) continue;
        if (val->type == JSON_ARRAY) {
            /* Replace each element. */
            json_t *new_arr = json_array();
            for (size_t i = 0; i < val->c.count; i++) {
                json_t *elem = val->c.items[i];
                if (elem && elem->type == JSON_STRING) {
                    char *res = f3_deliver_media(elem->str_val, NULL, task_id);
                    json_append(new_arr, json_string(res ? res : ""));
                    free(res);
                } else {
                    json_append(new_arr, json_copy(elem));
                }
            }
            json_set(args, fields[fi], new_arr);
        } else if (val->type == JSON_STRING) {
            char *res = f3_deliver_media(val->str_val, NULL, task_id);
            json_set(args, fields[fi], json_string(res ? res : ""));
            free(res);
        }
    }
    char *out = json_serialize(args);
    json_free(args);
    return out ? out : strdup("{}");
}

/* PoP: _download_video @ tools/flux3_video_tool.py:_download_video */
char *f3_download_video(const char *url, const char *save_to, double started) {
    /* Python: stream download with SSRF guard, write to .part, rename on success.
     * Returns JSON: {"path": ..., "bytes": ...} or raises. */
    if (!url) return strdup("{\"error\":\"no URL\"}");
    char *target = flux3_resolve_destination(save_to, f3_filename_from_url(url));
    if (!target) return strdup("{\"error\":\"could not resolve destination\"}");
    char partial[2048];
    snprintf(partial, sizeof(partial), "%s.part", target);
    /* Download via curl/system. */
    char cmd[4096];
    snprintf(cmd, sizeof(cmd),
             "curl -sL --max-time 300 --connect-timeout 15 "
             "'%s' -o '%s' 2>/dev/null", url, partial);
    int rc = system(cmd);
    char *result = NULL;
    if (rc != 0) {
        unlink(partial);
        json_t *err = json_object();
        json_set(err, "error", json_string("Download failed"));
        result = json_serialize(err);
        json_free(err);
    } else {
        struct stat st;
        if (stat(partial, &st) != 0 || (size_t)st.st_size < F3_MIN_PLAUSIBLE_VIDEO_BYTES_VAL) {
            unlink(partial);
            json_t *err = json_object();
            json_set(err, "error", json_string("download returned too few bytes"));
            result = json_serialize(err);
            json_free(err);
        } else {
            rename(partial, target);
            json_t *ok = json_object();
            json_set(ok, "path", json_string(target));
            json_set(ok, "bytes", json_number((double)st.st_size));
            result = json_serialize(ok);
            json_free(ok);
        }
    }
    free(target);
    return result ? result : strdup("{\"error\":\"unknown download failure\"}");
}

/* PoP: _save_if_ready @ tools/flux3_video_tool.py:_save_if_ready */
char *f3_save_if_ready(const char *raw, const char *save_to, double started) {
    /* Python: if status Ready, download + save; swap signed URL for path. */
    if (!raw) return strdup("{}");
    json_t *payload = json_parse(raw, NULL);
    if (!payload || payload->type != JSON_OBJECT) {
        if (payload) json_free(payload);
        return strdup(raw);
    }
    json_t *details = json_obj_get(payload, "details");
    if (!details || details->type != JSON_OBJECT) {
        char *out = json_serialize(payload);
        json_free(payload);
        return out ? out : strdup("{}");
    }
    json_t *status = json_obj_get(details, "status");
    const char *status_str = status && status->type == JSON_STRING ? status->str_val : "";
    if (!status_str || strcmp(status_str, "Ready") != 0) {
        char *out = json_serialize(payload);
        json_free(payload);
        return out ? out : strdup("{}");
    }
    json_t *result = json_obj_get(details, "result");
    json_t *sample = result && result->type == JSON_OBJECT ? json_obj_get(result, "sample") : NULL;
    const char *url = sample && sample->type == JSON_STRING ? sample->str_val : NULL;
    json_obj_del(details, "sample");
    if (!url || !*url) {
        json_obj_del(details, "sample");
        char *out = json_serialize(payload);
        json_free(payload);
        return out ? out : strdup("{}");
    }
    /* Download. */
    char *dl_result = f3_download_video(url, save_to, started);
    json_t *dl = json_parse(dl_result, NULL);
    if (dl && dl->type == JSON_OBJECT && json_obj_get(dl, "path")) {
        json_t *path = json_obj_get(dl, "path");
        if (path && path->type == JSON_STRING) {
            json_set(details, "saved_path", json_string(path->str_val));
            json_t *bytes_node = json_obj_get(dl, "bytes");
            if (bytes_node) json_set(details, "saved_bytes", json_number(bytes_node->num_val));
            /* Build delivery lead-in. */
            char *lead = f3_delivery_lead_in(path->str_val, true);
            const char *prev_result = result && result->type == JSON_STRING
                ? result->str_val : "";
            char *new_result = NULL;
            asprintf(&new_result, "%s%s", lead ? lead : "", prev_result);
            json_set(details, "result", json_string(new_result ? new_result : ""));
            free(lead);
            free(new_result);
        }
    } else {
        /* Download failed — set error in result. */
        json_t *err = json_obj_get(dl, "error");
        const char *emsg = err && err->type == JSON_STRING ? err->str_val : "download failed";
        json_set(details, "result", json_string(
            "The clip finished but saving it failed."));
    }
    json_free(dl);
    free(dl_result);
    char *out = json_serialize(payload);
    json_free(payload);
    return out ? out : strdup("{}");
}

/* PoP: _submit @ tools/flux3_video_tool.py:_submit */
char *f3_submit(const char *mode, const char *args_json) {
    /* Python: POST to gateway generations endpoint with mode + args. */
    json_t *endpoints = flux3_endpoints();
    if (!endpoints || !json_obj_get(endpoints, "base_url")) {
        if (endpoints) json_free(endpoints);
        char *err = NULL;
        asprintf(&err, "{\"error\":\"%s\"}", F3_SIGN_IN_MESSAGE);
        return err;
    }
    json_t *base = json_obj_get(endpoints, "base_url");
    const char *bv = base && base->type == JSON_STRING ? base->str_val : "";
    char url[1024];
    snprintf(url, sizeof(url), "%s/generations", bv);
    json_t *body = json_parse(args_json ? args_json : "{}", NULL);
    json_set(body, "mode", json_string(mode ? mode : ""));
    char *body_str = json_serialize(body);
    json_free(body);
    json_free(endpoints);
    char *resp = f3_call_gateway("POST", url, body_str, F3_TRANSPORT_READ_TIMEOUT_SECONDS);
    free(body_str);
    return resp;
}

/* PoP: _handle_text_to_video @ tools/flux3_video_tool.py:_handle_text_to_video */
char *f3_handle_text_to_video(const char *args_json, const char *task_id) {
    /* Python: submit without media. */
    json_t *args = json_parse(args_json ? args_json : "{}", NULL);
    char *clean_json = f3_without_media(args_json ? args_json : "{}");
    json_free(args);
    char *body = clean_json;
    char *result = f3_submit("text_to_video", body);
    free(body);
    return result;
}

/* PoP: _handle_image_to_video @ tools/flux3_video_tool.py:_handle_image_to_video */
char *f3_handle_image_to_video(const char *args_json, const char *task_id) {
    /* Python: prepare media, then submit image_to_video. */
    json_t *args = json_parse(args_json ? args_json : "{}", NULL);
    char *prepared = f3_prepare_media(args_json, task_id);
    if (args) json_free(args);
    char *result = f3_submit("image_to_video", prepared);
    free(prepared);
    return result;
}

/* PoP: _handle_keyframes_to_video @ tools/flux3_video_tool.py:_handle_keyframes_to_video */
char *f3_handle_keyframes_to_video(const char *args_json, const char *task_id) {
    /* Python: validate input_images, prepare media, submit keyframes_to_video. */
    json_t *args = json_parse(args_json ? args_json : "{}", NULL);
    if (!args || args->type != JSON_OBJECT) {
        if (args) json_free(args);
        return f3_error("input_images must be a non-empty list of 1-10 images (local paths or URLs).");
    }
    json_t *imgs = json_obj_get(args, "input_images");
    if (!imgs || imgs->type != JSON_ARRAY || imgs->c.count == 0) {
        json_free(args);
        return f3_error("input_images must be a non-empty list of 1-10 images (local paths or URLs).");
    }
    char *prepared = f3_prepare_media(args_json, task_id);
    json_free(args);
    char *result = f3_submit("keyframes_to_video", prepared);
    free(prepared);
    return result;
}

/* PoP: _handle_video_continuation @ tools/flux3_video_tool.py:_handle_video_continuation */
char *f3_handle_video_continuation(const char *args_json, const char *task_id) {
    /* Python: prepare media, submit video_continuation. */
    char *prepared = f3_prepare_media(args_json, task_id);
    char *result = f3_submit("video_continuation", prepared);
    free(prepared);
    return result;
}

/* PoP: _poll_until_done @ tools/flux3_video_tool.py:_poll_until_done */
char *f3_poll_until_done(const char *url, const char *save_to, double started) {
    /* Python: poll until Ready/Error/interrupt/budget exhausted. */
    double spent = 0.0;
    int unanswered = 0;
    char *raw = NULL;
    while (1) {
        double look_started = (double)time(NULL);
        raw = f3_call_gateway("GET", url, NULL, F3_POLL_READ_TIMEOUT_SECONDS);
        spent += (double)time(NULL) - look_started;
        if (f3_is_transport_error(raw)) {
            unanswered++;
            if (unanswered >= F3_MAX_CONSECUTIVE_TRANSPORT_ERRORS)
                return raw;
            double gap = F3_POLL_GAP_SECONDS;
            if (gap <= 0 || spent + gap >= F3_POLL_BUDGET_SECONDS)
                return raw;
            if (!f3_wait_between_looks(gap))
                return raw;
            spent += gap;
            free(raw);
            continue;
        }
        unanswered = 0;
        double throttled_for = f3_retry_after_seconds(raw);
        if (throttled_for == 0.0 && f3_poll_is_finished(raw))
            return f3_save_if_ready(raw, save_to, started);
        double gap = throttled_for <= 0.0 ? F3_POLL_GAP_SECONDS :
                     (throttled_for > F3_POLL_GAP_SECONDS ? throttled_for : F3_POLL_GAP_SECONDS);
        if (gap <= 0 || spent + gap >= F3_POLL_BUDGET_SECONDS)
            return raw;
        if (!f3_wait_between_looks(gap))
            return raw;
        spent += gap;
        free(raw);
    }
}

/* PoP: _handle_get_result @ tools/flux3_video_tool.py:_handle_get_result */
char *f3_handle_get_result(const char *args_json) {
    /* Python: parse job_id, build URL, poll until done or backstop. */
    if (!args_json) return f3_error("args required");
    json_t *args = json_parse(args_json, NULL);
    if (!args || args->type != JSON_OBJECT) {
        if (args) json_free(args);
        return f3_error("args required");
    }
    json_t *job_id_node = json_obj_get(args, "id");
    const char *job_id = job_id_node && job_id_node->type == JSON_STRING
        ? job_id_node->str_val : NULL;
    if (!job_id || !*job_id) {
        json_free(args);
        return f3_error("id is required: the job id returned by the generate tool.");
    }
    json_t *endpoints = flux3_endpoints();
    if (!endpoints || !json_obj_get(endpoints, "base_url")) {
        if (endpoints) json_free(endpoints);
        return f3_error("BFL video generation is not available in this build.");
    }
    json_t *base = json_obj_get(endpoints, "base_url");
    const char *bv = base && base->type == JSON_STRING ? base->str_val : "";
    char url[1024];
    snprintf(url, sizeof(url), "%s/generations/%s", bv, job_id);
    json_free(endpoints);
    json_t *save_node = json_obj_get(args, "save_to");
    const char *save_to = save_node && save_node->type == JSON_STRING
        ? save_node->str_val : NULL;
    json_free(args);
    double started = (double)time(NULL);
    /* In C: synchronous poll (no asyncio). */
    return f3_poll_until_done(url, save_to, started);
}

/* PoP: _handle_prompting_guide @ tools/flux3_video_tool.py:_handle_prompting_guide */
const char *f3_handle_prompting_guide(void) {
    /* Python: return FLUX3_PROMPTING_GUIDE constant. */
    return FLUX3_PROMPTING_GUIDE;
}
