/*
 * flux3_video_tool.c — Additional helper ports from tools/flux3_video_tool.py.
 *
 * The 8 helpers already ported by port_tools_flux3_video.c
 * (_looks_like_local_path, _display_path, _filename_from_url,
 * _is_transport_error, _poll_is_finished, _retry_after_seconds,
 * _without_media, _submit_args) are NOT duplicated here.
 *
 * This file adds: _resolve_destination, _free_path, _still_generating.
 */
#define _GNU_SOURCE
#include "flux3_video_tool.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <sys/stat.h>

/* PoP: _still_generating @ tools/flux3_video_tool.py:_still_generating */
char *flux3_still_generating(const char *job_id)
{
    char *out = NULL;
    if (!job_id) return NULL;
    /* Python uses em dash (U+2014, UTF-8 E2 80 94) not hyphen */
    asprintf(&out,
        "{\"result\": \"Still generating. This call reached its own time limit, "
        "which the job is unaffected by \xe2\x80\x94 call bfl_flux3_get_result again with "
        "id=%s to keep waiting.\", \"details\": {\"id\": \"%s\", \"status\": \"Generating\"}}",
        job_id, job_id);
    return out;
}

/* PoP: _resolve_destination @ tools/flux3_video_tool.py:_resolve_destination */
char *flux3_resolve_destination(const char *save_to, const char *filename)
{
    if (!filename) filename = "flux3-video.mp4";
    char dir[4096];
    if (save_to && *save_to) {
        strncpy(dir, save_to, sizeof(dir) - 1);
        dir[sizeof(dir) - 1] = '\0';
        size_t len = strlen(dir);
        while (len > 0 && (dir[len-1] == '/' || dir[len-1] == '\\'))
            dir[--len] = '\0';
        struct stat st;
        if (stat(dir, &st) != 0 || !S_ISDIR(st.st_mode)) {
            return strdup(save_to);
        }
    } else {
        const char *home = getenv("HOME");
        if (home)
            snprintf(dir, sizeof(dir), "%s/Downloads", home);
        else
            strcpy(dir, ".");
        struct stat st;
        if (stat(dir, &st) != 0 || !S_ISDIR(st.st_mode))
            strcpy(dir, ".");
    }
    return flux3_free_path(dir, filename);
}

/* PoP: _free_path @ tools/flux3_video_tool.py:_free_path */
char *flux3_free_path(const char *directory, const char *name)
{
    char candidate[4096];
    snprintf(candidate, sizeof(candidate), "%s/%s", directory ? directory : ".",
             name ? name : "flux3-video.mp4");
    struct stat st;
    if (stat(candidate, &st) != 0)
        return strdup(candidate);

    const char *dot = strrchr(name, '.');
    const char *base = strrchr(name, '/');
    if (base) base++;
    else base = name;
    char stem[256], suffix[32];
    if (dot && dot > base) {
        size_t sl = (size_t)(dot - base);
        if (sl >= sizeof(stem)) sl = sizeof(stem) - 1;
        memcpy(stem, base, sl); stem[sl] = '\0';
        size_t suf_l = strlen(dot);
        if (suf_l >= sizeof(suffix)) suf_l = sizeof(suffix) - 1;
        memcpy(suffix, dot, suf_l); suffix[suf_l] = '\0';
    } else {
        strncpy(stem, base, sizeof(stem) - 1);
        stem[sizeof(stem) - 1] = '\0';
        strcpy(suffix, "");
    }
    for (int s = 2; s < FLUX3_MAX_FILENAME_ATTEMPTS + 2; s++) {
        snprintf(candidate, sizeof(candidate), "%s/%s-%d%s", directory, stem, s, suffix);
        if (stat(candidate, &st) != 0) return strdup(candidate);
    }
    return NULL;
}

/* PoP: _shared_submit_properties @ tools/flux3_video_tool.py:_shared_submit_properties */
json_t *flux3_shared_submit_properties(void)
{
    json_t *props = json_object();

    json_t *prompt = json_object();
    json_set(prompt, "type", json_string("string"));
    json_set(prompt, "minLength", json_number(1));
    json_set(prompt, "description", json_string(
        "Generation brief in plain prose (it is interpreted and expanded by a reasoning "
        "harness). Order it subject, distinguishing visual specifics, action, camera, "
        "lighting, environment, audio, style. Audio is generated by default \xe2\x80\x94 say "
        "\"no music\" if unwanted."));
    json_set(props, "prompt", prompt);

    json_t *aspect = json_object();
    json_set(aspect, "type", json_string("string"));
    json_t *ar = json_array();
    const char *ratios[] = {"auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16", "9:21"};
    for (int i = 0; i < 8; i++) json_append(ar, json_string(ratios[i]));
    json_set(aspect, "enum", ar);
    json_set(aspect, "default", json_string("auto"));
    json_set(aspect, "description", json_string("Output aspect ratio. \"auto\" lets the model choose."));
    json_set(props, "aspect_ratio", aspect);

    json_t *dur = json_object();
    json_t *one = json_array();
    json_t *i1 = json_object();
    json_set(i1, "type", json_string("integer"));
    json_set(i1, "minimum", json_number(5));
    json_set(i1, "maximum", json_number(20));
    json_append(one, i1);
    json_t *i2 = json_object();
    json_set(i2, "type", json_string("string"));
    json_set(i2, "const", json_string("auto"));
    json_append(one, i2);
    json_set(dur, "oneOf", one);
    json_set(dur, "default", json_string("auto"));
    json_set(dur, "description", json_string("Clip duration in whole seconds (5-20), or \"auto\"."));
    json_set(props, "duration", dur);

    json_t *res = json_object();
    json_set(res, "type", json_string("string"));
    json_t *ra = json_array();
    json_append(ra, json_string("720p"));
    json_set(res, "enum", ra);
    json_set(res, "default", json_string("720p"));
    json_set(res, "description", json_string("Output resolution bin."));
    json_set(props, "resolution", res);

    json_t *ga = json_object();
    json_set(ga, "type", json_string("boolean"));
    json_set(ga, "default", json_bool(true));
    json_set(ga, "description", json_string("Generate synchronized audio."));
    json_set(props, "generate_audio", ga);

    json_t *gr = json_object();
    json_set(gr, "type", json_string("boolean"));
    json_set(gr, "default", json_bool(true));
    json_set(gr, "description", json_string("Allow a short research pass before generation."));
    json_set(props, "grounding", gr);

    json_t *sd = json_object();
    json_set(sd, "type", json_string("integer"));
    json_set(sd, "minimum", json_number(0));
    json_set(sd, "maximum", json_number(4294967295));
    json_set(sd, "description", json_string("Optional reproducibility seed."));
    json_set(props, "seed", sd);

    json_t *ver = json_object();
    json_set(ver, "type", json_string("string"));
    json_set(ver, "description", json_string("Model version pin. Defaults to \"latest\"."));
    json_set(props, "version", ver);

    return props;
}
